/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/signers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['signers.list'];
    put?: never;
    post: operations['signers.register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['vaults.list'];
    put?: never;
    post: operations['vaults.create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['vaults.get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{vaultId}/reshares': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['reshares.list'];
    put?: never;
    post: operations['reshares.create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{vaultId}/reshares/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['reshares.get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{vaultId}/reshares/{id}/votes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get all votes for a reshare */
    get: operations['reshares.getVotes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{vaultId}/signatures/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get a signature request and its metadata by ID */
    get: operations['signatures.get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{vaultId}/signatures': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['signatures.list'];
    put?: never;
    /** @description Create a new signature request in a vault. */
    post: operations['signatures.create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{vaultId}/signatures/{id}/votes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get all possible votes for a signature request, including pending votes and weight per signer. */
    get: operations['signatures.getVotes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['health.check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/license': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get current license information and status */
    get: operations['license.info'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/license/usage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get current system-wide resource usage compared to license limits */
    get: operations['license.usage'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/license/clear-cache': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description [TEST-ONLY] Clear usage cache for specific entitlement or all caches */
    post: operations['license.clearCache'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'signers.list': {
    parameters: {
      query?: {
        limit?: number | null;
        cursor?: string | null;
        order?: ('asc' | 'desc') | null;
        userId?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              id: string;
              externalId: string;
              userId: string;
              name: string;
              description?: string | null;
              publicKey: string;
              /** @enum {unknown} */
              algorithm: 'client_record';
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              createdBy: string;
            }[];
            nextCursor?: string | null;
            hasMore: boolean;
          };
        };
      };
    };
  };
  'signers.register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          externalId: string;
          name: string;
          description?: string | null;
          publicKey: string;
          /** @enum {unknown} */
          algorithm: 'client_record';
        };
      };
    };
    responses: {
      /** @description OK */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            externalId: string;
            userId: string;
            name: string;
            description?: string | null;
            publicKey: string;
            /** @enum {unknown} */
            algorithm: 'client_record';
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            createdBy: string;
          };
        };
      };
    };
  };
  'vaults.list': {
    parameters: {
      query?: {
        limit?: number | null;
        cursor?: string | null;
        order?: ('asc' | 'desc') | null;
        status?:
          | ('draft' | 'active' | 'archived')
          | ('draft' | 'active' | 'archived')[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              id: string;
              name: string;
              description?: string | null;
              threshold: number;
              /** @enum {unknown} */
              status: 'draft' | 'active' | 'archived';
              reshareNonce: number;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              createdBy: string;
              curves?:
                | {
                    id: string;
                    /** @enum {unknown} */
                    curve: 'edwards' | 'nist256p1' | 'secp256k1';
                    /** @enum {unknown} */
                    algorithm: 'eddsa' | 'ecdsa';
                    xpub: string;
                    /** Format: date-time */
                    createdAt: string;
                  }[]
                | null;
            }[];
            nextCursor?: string | null;
            hasMore: boolean;
          };
        };
      };
    };
  };
  'vaults.create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
          description?: string | null;
          threshold: number;
          signers: {
            key: string;
            weight: number;
          }[];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            name: string;
            description?: string | null;
            threshold: number;
            /** @enum {unknown} */
            status: 'draft' | 'active' | 'archived';
            reshareNonce: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            createdBy: string;
            curves?:
              | {
                  id: string;
                  /** @enum {unknown} */
                  curve: 'edwards' | 'nist256p1' | 'secp256k1';
                  /** @enum {unknown} */
                  algorithm: 'eddsa' | 'ecdsa';
                  xpub: string;
                  /** Format: date-time */
                  createdAt: string;
                }[]
              | null;
          };
        };
      };
    };
  };
  'vaults.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            name: string;
            description?: string | null;
            threshold: number;
            /** @enum {unknown} */
            status: 'draft' | 'active' | 'archived';
            reshareNonce: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            createdBy: string;
            curves?:
              | {
                  id: string;
                  /** @enum {unknown} */
                  curve: 'edwards' | 'nist256p1' | 'secp256k1';
                  /** @enum {unknown} */
                  algorithm: 'eddsa' | 'ecdsa';
                  xpub: string;
                  /** Format: date-time */
                  createdAt: string;
                }[]
              | null;
          };
        };
      };
    };
  };
  'reshares.list': {
    parameters: {
      query?: {
        limit?: number | null;
        cursor?: string | null;
        order?: ('asc' | 'desc') | null;
        status?:
          | (
              | (
                  | 'voting'
                  | 'completed'
                  | 'failed'
                  | 'expired'
                  | 'signing'
                  | 'rejected'
                )
              | (
                  | 'voting'
                  | 'completed'
                  | 'failed'
                  | 'expired'
                  | 'signing'
                  | 'rejected'
                )[]
            )
          | null;
      };
      header?: never;
      path: {
        vaultId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              id: string;
              vaultId: string;
              threshold: number;
              /** @enum {unknown} */
              status:
                | 'voting'
                | 'completed'
                | 'failed'
                | 'expired'
                | 'signing'
                | 'rejected';
              memo?: string | null;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              createdBy: string;
              /** Format: date-time */
              expiresAt: string;
            }[];
            nextCursor?: string | null;
            hasMore: boolean;
          };
        };
      };
    };
  };
  'reshares.create': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vaultId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          threshold: number;
          signers: {
            signerKey: string;
            signingPower: number;
          }[];
          expiresAt?: string | null;
          memo?: string | null;
        };
      };
    };
    responses: {
      /** @description OK */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            vaultId: string;
            threshold: number;
            /** @enum {unknown} */
            status:
              | 'voting'
              | 'completed'
              | 'failed'
              | 'expired'
              | 'signing'
              | 'rejected';
            memo?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            createdBy: string;
            /** Format: date-time */
            expiresAt: string;
          };
        };
      };
    };
  };
  'reshares.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vaultId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            vaultId: string;
            threshold: number;
            /** @enum {unknown} */
            status:
              | 'voting'
              | 'completed'
              | 'failed'
              | 'expired'
              | 'signing'
              | 'rejected';
            memo?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            createdBy: string;
            /** Format: date-time */
            expiresAt: string;
          };
        };
      };
    };
  };
  'reshares.getVotes': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vaultId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            signerId: string;
            signerExternalId: string | null;
            reshareId: string;
            weight: number;
            oldWeight: number;
            /** @enum {unknown} */
            changeType: 'added' | 'removed' | 'kept';
            /** @enum {unknown} */
            result: 'approve' | 'reject';
            /** Format: date-time */
            votedAt: string;
            approvalSignature: string | null;
          }[];
        };
      };
    };
  };
  'signatures.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vaultId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            vaultId: string;
            /** @enum {unknown} */
            status:
              | 'voting'
              | 'presigning'
              | 'signing'
              | 'completed'
              | 'rejected'
              | 'expired'
              | 'failed';
            data: string[];
            chainId: number | null;
            /** @enum {unknown} */
            coseAlgorithm: 'eddsa' | 'eddsa_blake2b' | 'es256k' | 'eskec256';
            derivationPath: string | null;
            /** @enum {unknown} */
            contentType:
              | 'application/octet-stream+hex'
              | 'application/octet-stream+base64'
              | 'text/plain'
              | 'application/x-eip712+json';
            signature: string[] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            createdBy: string;
          };
        };
      };
    };
  };
  'signatures.list': {
    parameters: {
      query?: {
        limit?: number | null;
        cursor?: string | null;
        order?: ('asc' | 'desc') | null;
        status?:
          | (
              | (
                  | 'voting'
                  | 'presigning'
                  | 'signing'
                  | 'completed'
                  | 'rejected'
                  | 'expired'
                  | 'failed'
                )
              | (
                  | 'voting'
                  | 'presigning'
                  | 'signing'
                  | 'completed'
                  | 'rejected'
                  | 'expired'
                  | 'failed'
                )[]
            )
          | null;
      };
      header?: never;
      path: {
        vaultId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              id: string;
              vaultId: string;
              /** @enum {unknown} */
              status:
                | 'voting'
                | 'presigning'
                | 'signing'
                | 'completed'
                | 'rejected'
                | 'expired'
                | 'failed';
              data: string[];
              chainId: number | null;
              /** @enum {unknown} */
              coseAlgorithm: 'eddsa' | 'eddsa_blake2b' | 'es256k' | 'eskec256';
              derivationPath: string | null;
              /** @enum {unknown} */
              contentType:
                | 'application/octet-stream+hex'
                | 'application/octet-stream+base64'
                | 'text/plain'
                | 'application/x-eip712+json';
              signature: string[] | null;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              createdBy: string;
            }[];
            nextCursor?: string | null;
            hasMore: boolean;
          };
        };
      };
    };
  };
  'signatures.create': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vaultId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          data: string[];
          /** @enum {unknown} */
          contentType:
            | 'application/octet-stream+hex'
            | 'application/octet-stream+base64'
            | 'text/plain'
            | 'application/x-eip712+json';
          /** @enum {unknown} */
          coseAlgorithm: 'eddsa' | 'eddsa_blake2b' | 'es256k' | 'eskec256';
          memo?: string | null;
          derivationPath?: string | null;
          chainId?: number | null;
          expiryTimestamp?: string | null;
        };
      };
    };
    responses: {
      /** @description OK */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            vaultId: string;
            /** @enum {unknown} */
            status:
              | 'voting'
              | 'presigning'
              | 'signing'
              | 'completed'
              | 'rejected'
              | 'expired'
              | 'failed';
            data: string[];
            chainId: number | null;
            /** @enum {unknown} */
            coseAlgorithm: 'eddsa' | 'eddsa_blake2b' | 'es256k' | 'eskec256';
            derivationPath: string | null;
            /** @enum {unknown} */
            contentType:
              | 'application/octet-stream+hex'
              | 'application/octet-stream+base64'
              | 'text/plain'
              | 'application/x-eip712+json';
            signature: string[] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            createdBy: string;
          };
        };
      };
    };
  };
  'signatures.getVotes': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vaultId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            signerId: string;
            signerExternalId: string | null;
            approvalSignature: string | null;
            reshareId: string;
            weight: number;
            /** @enum {unknown} */
            result: 'approve' | 'reject';
            /** Format: date-time */
            votedAt: string;
          }[];
        };
      };
    };
  };
  'health.check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            status: string;
            timestamp: string;
            uptime: number;
            database: string;
          };
        };
      };
    };
  };
  'license.info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            valid: boolean;
            readOnlyMode: boolean;
            lastValidation: string | null;
            license?: {
              customerId: string;
              issuedAt: string;
              expiresAt: string;
              entitlements: {
                [key: string]: string | number | boolean;
              };
            };
          };
        };
      };
    };
  };
  'license.usage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            usage: {
              entitlement: string;
              limit: number | string | boolean;
              currentUsage: number;
              percentage?: number;
              exceeded: boolean;
            }[];
          };
        };
      };
    };
  };
  'license.clearCache': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          entitlement?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
}
