import {
  type ChainAlias,
  type EvmChainAlias,
  EvmChainAliases,
  type SubstrateChainAlias,
  SubstrateChainAliases,
  type SvmChainAlias,
  SvmChainAliases,
  type TronChainAlias,
  TronChainAliases,
  type UtxoChainAlias,
  UtxoChainAliases,
  type XrpChainAlias,
  XrpChainAliases,
} from '@iofinnet/io-core-dapp-utils-chains-sdk';
import { z } from 'zod';

export enum ChainFeatures {
  OVERALL_STATUS = 'overall-status',
  RPC = 'rpc',
  REALTIME_EVENTS = 'real-time-events',
  TRANSACTION_HISTORY = 'transaction-history',
  TRANSACTION_DESCRIPTIONS = 'transaction-descriptions',
  TOKEN_BALANCES = 'token-balances',
  TOKEN_PRICES = 'token-prices',
  HD_WALLETS = 'hd-wallets',
  AUTO_SWEEPING = 'auto-sweeping',
  BLOCKAID_SCAN = 'blockaid-scan',
  DASHBOARD_SUPPORT = 'dashboard-support',
  MULTI_APP_BETA_UI = 'multi-app-beta-ui',
  STAKING = 'staking',
  RECONCILIATION = 'reconciliation',
}

export enum FeatureStatus {
  ALPHA = 'alpha',
  BETA = 'beta',
  GA = 'ga',
  NOT_SUPPORTED = 'not-supported',
  COMING_SOON = 'coming-soon',
  DEPRECATED = 'deprecated',
  NOT_APPLICABLE = 'not-applicable',
  AVAILABLE_ON_REQUEST = 'available-on-request',
}

const Environment = {
  DEV: 'dev',
  STAGING: 'staging',
  PROD: 'prod',
} as const;

export type Environment = (typeof Environment)[keyof typeof Environment];

export interface BlockExplorer {
  name: string;
  url: string;
  apiUrl?: string;
}

// /** Literal feature → status record for one chain */
export type ChainFeatureStatuses = Record<ChainFeatures, FeatureStatus>;

export type ChainWithFeatures = {
  features: Record<ChainFeatures, FeatureStatus>;
  isTestnet: boolean;
  environments: Environment[];
  isV1?: boolean;
  rpcUrls?: Record<string, string>;
};

export const activeFeatureStatuses = [FeatureStatus.ALPHA, FeatureStatus.BETA, FeatureStatus.GA];

// @ts-expect-error removed DEGEN
const evmChainWithFeatures: Record<EvmChainAlias, ChainWithFeatures> = {
  [EvmChainAliases.ARBITRUM]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.BETA,
      [ChainFeatures.RPC]: FeatureStatus.BETA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.BETA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.BETA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.BETA,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.BETA,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.BETA,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.BETA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: true,
  },
  [EvmChainAliases.ABSTRACT]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.ARBITRUM_NOVA]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.AVALANCHE_C]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.BETA,
      [ChainFeatures.RPC]: FeatureStatus.BETA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.BETA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.BETA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.BETA,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.BETA,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.BETA,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.BETA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: true,
  },

  [EvmChainAliases.ASTAR]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.BASE]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.BETA,
      [ChainFeatures.RPC]: FeatureStatus.BETA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.BETA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.BETA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.BETA,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.BETA,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.BETA,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.BETA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: true,
  },
  [EvmChainAliases.BERACHAIN]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.COMING_SOON,
      [ChainFeatures.RPC]: FeatureStatus.COMING_SOON,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.COMING_SOON,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.COMING_SOON,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.COMING_SOON,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.COMING_SOON,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.COMING_SOON,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.AVAILABLE_ON_REQUEST,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.COMING_SOON,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.COMING_SOON,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.AVAILABLE_ON_REQUEST,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.BLAST]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.BSC]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.BETA,
      [ChainFeatures.RPC]: FeatureStatus.BETA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.BETA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.BETA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.BETA,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.BETA,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.BETA,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.BETA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: true,
  },
  [EvmChainAliases.CELO]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.COQNET]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.CRONOS]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.DFK]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.DFK_TESTNET]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: false,
  },
  [EvmChainAliases.ETH]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.BETA,
      [ChainFeatures.RPC]: FeatureStatus.BETA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.BETA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.BETA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.BETA,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.BETA,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.BETA,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.BETA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: true,
  },
  [EvmChainAliases.ETH_SEPOLIA]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.ALPHA,
      [ChainFeatures.RPC]: FeatureStatus.ALPHA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.ALPHA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.ALPHA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.ALPHA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.ALPHA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.ALPHA,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.ALPHA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [],
    isV1: true,
  },
  [EvmChainAliases.FANTOM]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.BETA,
      [ChainFeatures.RPC]: FeatureStatus.BETA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.BETA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.BETA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.BETA,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.BETA,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.BETA,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.BETA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: true,
  },
  [EvmChainAliases.FLAME]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.FLOW_EVM]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.FLUENT_DEVNET]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.FRAXTAL]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.FUSE]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.GNOSIS]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.INK]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.LAMINA1]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.LIGHTLINK]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.LINEA]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.LUKSO]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.MANTA_PACIFIC]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.MANTLE]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.MATCHAIN]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.METAL]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.METIS]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.MINT_SEPOLIA]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.MODE]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.MONAD_TESTNET]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.MOONRIVER]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.MORPH]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.MORPH_HOLESKY_TESTNET]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.OPTIMISM]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.BETA,
      [ChainFeatures.RPC]: FeatureStatus.BETA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.BETA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.BETA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.BETA,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.BETA,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.BETA,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.BETA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: true,
  },
  [EvmChainAliases.ORDERLY_NETWORK]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.PERENNIAL]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.PLUME_DEVNET]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.POLYGON]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.BETA,
      [ChainFeatures.RPC]: FeatureStatus.BETA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.BETA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.BETA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.BETA,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.BETA,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.BETA,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.BETA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: true,
  },
  [EvmChainAliases.POLYGON_ZKEVM]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.PULSECHAIN]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.QUAI]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.RARI]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.RONIN]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.SCROLL]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.SHIMMER_EVM]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.SONIC]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: false,
  },
  [EvmChainAliases.SOPHON_TESTNET]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.SUPERPOSITION_TESTNET]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.SUPERSEED_SEPOLIA]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.XAI]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.XDC]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.ZKSYNC_ERA]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
  [EvmChainAliases.ZORA]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV],
    isV1: false,
  },
};

// @ts-expect-error - cannot support these chains
const utxoChainWithFeatures: Record<UtxoChainAlias, ChainWithFeatures> = {
  [UtxoChainAliases.BITCOIN]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.BETA,
      [ChainFeatures.RPC]: FeatureStatus.BETA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.BETA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.BETA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_APPLICABLE,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.BETA,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.BETA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: true,
  },
  [UtxoChainAliases.MNEE]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.BETA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING, Environment.PROD],
    isV1: true,
  },
  // [UtxoChainAliases.CARDANO]: {
  //   features: {
  //     [ChainFeatures.RPC]: FeatureStatus.COMING_SOON,
  //     [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
  //     [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.COMING_SOON,
  //     [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.COMING_SOON,
  //     [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.ALPHA,
  //     [ChainFeatures.TOKEN_PRICES]: FeatureStatus.ALPHA,
  //     [ChainFeatures.HD_WALLETS]: FeatureStatus.AVAILABLE_ON_REQUEST,
  //     [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
  //     [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
  //   },
  //   isTestnet: false,
  // },
  // [UtxoChainAliases.LTC]: {
  //   features: {
  //     [ChainFeatures.RPC]: FeatureStatus.COMING_SOON,
  //     [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.COMING_SOON,
  //     [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.COMING_SOON,
  //     [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.COMING_SOON,
  //     [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.COMING_SOON,
  //     [ChainFeatures.TOKEN_PRICES]: FeatureStatus.COMING_SOON,
  //     [ChainFeatures.HD_WALLETS]: FeatureStatus.AVAILABLE_ON_REQUEST,
  //     [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
  //     [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
  //   },
  //   isTestnet: false,
  // },
  [UtxoChainAliases.MNEE_TESTNET]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.AVAILABLE_ON_REQUEST,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [Environment.DEV, Environment.STAGING, Environment.PROD],
    isV1: true,
  },
};

//@ts-expect-error removed SOLANA_TESTNET
const svmChainWithFeatures: Record<SvmChainAlias, ChainWithFeatures> = {
  [SvmChainAliases.SOLANA]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.GA,
      [ChainFeatures.RPC]: FeatureStatus.GA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.GA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.GA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.GA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.GA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.GA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.GA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.COMING_SOON,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.BETA,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.GA,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING, Environment.PROD],
    isV1: false,
  },
};

//@ts-expect-error removed XRP_TESTNET
const xrpChainWithFeatures: Record<XrpChainAlias, ChainWithFeatures> = {
  [XrpChainAliases.XRP]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.BETA,
      [ChainFeatures.RPC]: FeatureStatus.BETA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.BETA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.BETA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.AVAILABLE_ON_REQUEST,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING, Environment.PROD],
    isV1: true,
  },
};

const tronChainWithFeatures: Record<TronChainAlias, ChainWithFeatures> = {
  [TronChainAliases.TRON]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.BETA,
      [ChainFeatures.RPC]: FeatureStatus.BETA,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.BETA,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.BETA,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.BETA,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.BETA,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.BETA,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.BETA,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.AVAILABLE_ON_REQUEST,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: true,
  },
};

const substrateChainWithFeatures: Record<SubstrateChainAlias, ChainWithFeatures> = {
  [SubstrateChainAliases.BITTENSOR]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_APPLICABLE,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_APPLICABLE,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: false,
    environments: [Environment.DEV, Environment.STAGING, Environment.PROD],
    isV1: false,
  },
  [SubstrateChainAliases.BITTENSOR_TESTNET]: {
    features: {
      [ChainFeatures.OVERALL_STATUS]: FeatureStatus.COMING_SOON,
      [ChainFeatures.RPC]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.REALTIME_EVENTS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_HISTORY]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TRANSACTION_DESCRIPTIONS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_BALANCES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.TOKEN_PRICES]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.HD_WALLETS]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.AUTO_SWEEPING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.BLOCKAID_SCAN]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.DASHBOARD_SUPPORT]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.MULTI_APP_BETA_UI]: FeatureStatus.AVAILABLE_ON_REQUEST,
      [ChainFeatures.STAKING]: FeatureStatus.NOT_SUPPORTED,
      [ChainFeatures.RECONCILIATION]: FeatureStatus.NOT_SUPPORTED,
    },
    isTestnet: true,
    environments: [Environment.DEV, Environment.STAGING],
    isV1: false,
  },
};

export const ALL_CHAINS: Record<Exclude<ChainAlias, 'berachain' | 'degen'>, ChainWithFeatures> = {
  ...evmChainWithFeatures,
  ...utxoChainWithFeatures,
  ...svmChainWithFeatures,
  ...xrpChainWithFeatures,
  ...tronChainWithFeatures,
  ...substrateChainWithFeatures,
};

/**
 * Get list of chain aliases that have an active overall status (Alpha, Beta, or GA)
 */
export const getActiveSupportedChains = (): ChainAlias[] => {
  return Object.entries(ALL_CHAINS)
    .filter(([_, chainConfig]) =>
      activeFeatureStatuses.includes(chainConfig.features[ChainFeatures.OVERALL_STATUS])
    )
    .map(([chainAlias]) => chainAlias as ChainAlias);
};

/**
 * Zod enum schema for supported chains (chains with active overall status: Alpha, Beta, or GA)
 * This is the single source of truth for chain validation across the application
 */
export const supportedChains = z.enum(
  getActiveSupportedChains() as [ChainAlias, ChainAlias, ...ChainAlias[]]
);

/**
 * Get the iofinnet RPC URL for a chain alias.
 * Uses the pattern: https://nodes.iofinnet.com/internal/{chainAlias}
 */
export function getRpcUrl(chainAlias: ChainAlias): string {
  return `https://nodes.iofinnet.com/internal/${chainAlias}`;
}

/**
 * Get RPC URLs for all active EVM chains.
 * Returns a map of chainAlias -> RPC URL
 */
export function getEvmRpcUrls(): Record<string, string> {
  const evmAliases = Object.keys(evmChainWithFeatures) as EvmChainAlias[];
  const activeEvmChains = evmAliases.filter((alias) =>
    activeFeatureStatuses.includes(evmChainWithFeatures[alias].features[ChainFeatures.OVERALL_STATUS])
  );

  return activeEvmChains.reduce(
    (acc, alias) => {
      acc[alias] = getRpcUrl(alias);
      return acc;
    },
    {} as Record<string, string>
  );
}

/**
 * Get RPC URLs for all active SVM chains.
 * Returns a map of chainAlias -> RPC URL
 */
export function getSvmRpcUrls(): Record<string, string> {
  const svmAliases = Object.keys(svmChainWithFeatures) as SvmChainAlias[];
  const activeSvmChains = svmAliases.filter((alias) =>
    activeFeatureStatuses.includes(svmChainWithFeatures[alias].features[ChainFeatures.OVERALL_STATUS])
  );

  return activeSvmChains.reduce(
    (acc, alias) => {
      acc[alias] = getRpcUrl(alias);
      return acc;
    },
    {} as Record<string, string>
  );
}
