/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppComplianceRouteRouteImport } from './routes/_app/compliance/route'
import { Route as ManagerUsersIndexRouteImport } from './routes/manager/users/index'
import { Route as ManagerDashboardIndexRouteImport } from './routes/manager/dashboard.index'
import { Route as ManagerBooksIndexRouteImport } from './routes/manager/books/index'
import { Route as ManagerAccountIndexRouteImport } from './routes/manager/account.index'
import { Route as LoginVerifyIndexRouteImport } from './routes/login/verify.index'
import { Route as LoginErrorIndexRouteImport } from './routes/login/error.index'
import { Route as AppBooksIndexRouteImport } from './routes/app/books/index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account.index'
import { Route as AppComplianceIndexRouteImport } from './routes/_app/compliance/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiRestSplatRouteImport } from './routes/api/rest.$'
import { Route as ApiOpenapiAuthRouteImport } from './routes/api/openapi/auth'
import { Route as ApiOpenapiAppRouteImport } from './routes/api/openapi/app'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppComplianceReportsRouteImport } from './routes/_app/compliance/reports'
import { Route as AppComplianceAlertsRouteImport } from './routes/_app/compliance/alerts'
import { Route as AppComplianceTransactionsRouteRouteImport } from './routes/_app/compliance/transactions/route'
import { Route as AppComplianceAddressesRouteRouteImport } from './routes/_app/compliance/addresses/route'
import { Route as ManagerUsersNewIndexRouteImport } from './routes/manager/users/new.index'
import { Route as ManagerUsersIdIndexRouteImport } from './routes/manager/users/$id.index'
import { Route as ManagerBooksNewIndexRouteImport } from './routes/manager/books/new.index'
import { Route as ManagerBooksIdIndexRouteImport } from './routes/manager/books/$id.index'
import { Route as AppBooksIdIndexRouteImport } from './routes/app/books/$id.index'
import { Route as AppComplianceTransactionsIndexRouteImport } from './routes/_app/compliance/transactions/index'
import { Route as AppComplianceAddressesIndexRouteImport } from './routes/_app/compliance/addresses/index'
import { Route as ApiOpenapiAuthSchemaRouteImport } from './routes/api/openapi/auth.schema'
import { Route as ApiOpenapiAppSchemaRouteImport } from './routes/api/openapi/app.schema'
import { Route as ApiDevEmailTemplateRouteImport } from './routes/api/dev.email.$template'
import { Route as AppComplianceTransactionsIdRouteImport } from './routes/_app/compliance/transactions/$id'
import { Route as AppComplianceAddressesAddressRouteImport } from './routes/_app/compliance/addresses/$address'
import { Route as ManagerUsersIdUpdateIndexRouteImport } from './routes/manager/users/$id.update.index'
import { Route as ManagerBooksIdUpdateIndexRouteImport } from './routes/manager/books/$id.update.index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComplianceRouteRoute = AppComplianceRouteRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const ManagerUsersIndexRoute = ManagerUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerDashboardIndexRoute = ManagerDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerBooksIndexRoute = ManagerBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerAccountIndexRoute = ManagerAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const LoginVerifyIndexRoute = LoginVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginErrorIndexRoute = LoginErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppBooksIndexRoute = AppBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComplianceIndexRoute = AppComplianceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppComplianceRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestSplatRoute = ApiRestSplatRouteImport.update({
  id: '/api/rest/$',
  path: '/api/rest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiAuthRoute = ApiOpenapiAuthRouteImport.update({
  id: '/api/openapi/auth',
  path: '/api/openapi/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiAppRoute = ApiOpenapiAppRouteImport.update({
  id: '/api/openapi/app',
  path: '/api/openapi/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComplianceReportsRoute = AppComplianceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppComplianceRouteRoute,
} as any)
const AppComplianceAlertsRoute = AppComplianceAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppComplianceRouteRoute,
} as any)
const AppComplianceTransactionsRouteRoute =
  AppComplianceTransactionsRouteRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AppComplianceRouteRoute,
  } as any)
const AppComplianceAddressesRouteRoute =
  AppComplianceAddressesRouteRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AppComplianceRouteRoute,
  } as any)
const ManagerUsersNewIndexRoute = ManagerUsersNewIndexRouteImport.update({
  id: '/users/new/',
  path: '/users/new/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerUsersIdIndexRoute = ManagerUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerBooksNewIndexRoute = ManagerBooksNewIndexRouteImport.update({
  id: '/books/new/',
  path: '/books/new/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerBooksIdIndexRoute = ManagerBooksIdIndexRouteImport.update({
  id: '/books/$id/',
  path: '/books/$id/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const AppBooksIdIndexRoute = AppBooksIdIndexRouteImport.update({
  id: '/books/$id/',
  path: '/books/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComplianceTransactionsIndexRoute =
  AppComplianceTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppComplianceTransactionsRouteRoute,
  } as any)
const AppComplianceAddressesIndexRoute =
  AppComplianceAddressesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppComplianceAddressesRouteRoute,
  } as any)
const ApiOpenapiAuthSchemaRoute = ApiOpenapiAuthSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ApiOpenapiAuthRoute,
} as any)
const ApiOpenapiAppSchemaRoute = ApiOpenapiAppSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ApiOpenapiAppRoute,
} as any)
const ApiDevEmailTemplateRoute = ApiDevEmailTemplateRouteImport.update({
  id: '/api/dev/email/$template',
  path: '/api/dev/email/$template',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComplianceTransactionsIdRoute =
  AppComplianceTransactionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppComplianceTransactionsRouteRoute,
  } as any)
const AppComplianceAddressesAddressRoute =
  AppComplianceAddressesAddressRouteImport.update({
    id: '/$address',
    path: '/$address',
    getParentRoute: () => AppComplianceAddressesRouteRoute,
  } as any)
const ManagerUsersIdUpdateIndexRoute =
  ManagerUsersIdUpdateIndexRouteImport.update({
    id: '/users/$id/update/',
    path: '/users/$id/update/',
    getParentRoute: () => ManagerRouteRoute,
  } as any)
const ManagerBooksIdUpdateIndexRoute =
  ManagerBooksIdUpdateIndexRouteImport.update({
    id: '/books/$id/update/',
    path: '/books/$id/update/',
    getParentRoute: () => ManagerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/compliance': typeof AppComplianceRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/compliance/addresses': typeof AppComplianceAddressesRouteRouteWithChildren
  '/compliance/transactions': typeof AppComplianceTransactionsRouteRouteWithChildren
  '/compliance/alerts': typeof AppComplianceAlertsRoute
  '/compliance/reports': typeof AppComplianceReportsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/compliance/': typeof AppComplianceIndexRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/books': typeof AppBooksIndexRoute
  '/login/error': typeof LoginErrorIndexRoute
  '/login/verify': typeof LoginVerifyIndexRoute
  '/manager/account': typeof ManagerAccountIndexRoute
  '/manager/books': typeof ManagerBooksIndexRoute
  '/manager/dashboard': typeof ManagerDashboardIndexRoute
  '/manager/users': typeof ManagerUsersIndexRoute
  '/compliance/addresses/$address': typeof AppComplianceAddressesAddressRoute
  '/compliance/transactions/$id': typeof AppComplianceTransactionsIdRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/compliance/addresses/': typeof AppComplianceAddressesIndexRoute
  '/compliance/transactions/': typeof AppComplianceTransactionsIndexRoute
  '/app/books/$id': typeof AppBooksIdIndexRoute
  '/manager/books/$id': typeof ManagerBooksIdIndexRoute
  '/manager/books/new': typeof ManagerBooksNewIndexRoute
  '/manager/users/$id': typeof ManagerUsersIdIndexRoute
  '/manager/users/new': typeof ManagerUsersNewIndexRoute
  '/manager/books/$id/update': typeof ManagerBooksIdUpdateIndexRoute
  '/manager/users/$id/update': typeof ManagerUsersIdUpdateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/compliance/alerts': typeof AppComplianceAlertsRoute
  '/compliance/reports': typeof AppComplianceReportsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/compliance': typeof AppComplianceIndexRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/books': typeof AppBooksIndexRoute
  '/login/error': typeof LoginErrorIndexRoute
  '/login/verify': typeof LoginVerifyIndexRoute
  '/manager/account': typeof ManagerAccountIndexRoute
  '/manager/books': typeof ManagerBooksIndexRoute
  '/manager/dashboard': typeof ManagerDashboardIndexRoute
  '/manager/users': typeof ManagerUsersIndexRoute
  '/compliance/addresses/$address': typeof AppComplianceAddressesAddressRoute
  '/compliance/transactions/$id': typeof AppComplianceTransactionsIdRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/compliance/addresses': typeof AppComplianceAddressesIndexRoute
  '/compliance/transactions': typeof AppComplianceTransactionsIndexRoute
  '/app/books/$id': typeof AppBooksIdIndexRoute
  '/manager/books/$id': typeof ManagerBooksIdIndexRoute
  '/manager/books/new': typeof ManagerBooksNewIndexRoute
  '/manager/users/$id': typeof ManagerUsersIdIndexRoute
  '/manager/users/new': typeof ManagerUsersNewIndexRoute
  '/manager/books/$id/update': typeof ManagerBooksIdUpdateIndexRoute
  '/manager/users/$id/update': typeof ManagerUsersIdUpdateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_app/compliance': typeof AppComplianceRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/_app/compliance/addresses': typeof AppComplianceAddressesRouteRouteWithChildren
  '/_app/compliance/transactions': typeof AppComplianceTransactionsRouteRouteWithChildren
  '/_app/compliance/alerts': typeof AppComplianceAlertsRoute
  '/_app/compliance/reports': typeof AppComplianceReportsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_app/compliance/': typeof AppComplianceIndexRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/books/': typeof AppBooksIndexRoute
  '/login/error/': typeof LoginErrorIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/manager/account/': typeof ManagerAccountIndexRoute
  '/manager/books/': typeof ManagerBooksIndexRoute
  '/manager/dashboard/': typeof ManagerDashboardIndexRoute
  '/manager/users/': typeof ManagerUsersIndexRoute
  '/_app/compliance/addresses/$address': typeof AppComplianceAddressesAddressRoute
  '/_app/compliance/transactions/$id': typeof AppComplianceTransactionsIdRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/_app/compliance/addresses/': typeof AppComplianceAddressesIndexRoute
  '/_app/compliance/transactions/': typeof AppComplianceTransactionsIndexRoute
  '/app/books/$id/': typeof AppBooksIdIndexRoute
  '/manager/books/$id/': typeof ManagerBooksIdIndexRoute
  '/manager/books/new/': typeof ManagerBooksNewIndexRoute
  '/manager/users/$id/': typeof ManagerUsersIdIndexRoute
  '/manager/users/new/': typeof ManagerUsersNewIndexRoute
  '/manager/books/$id/update/': typeof ManagerBooksIdUpdateIndexRoute
  '/manager/users/$id/update/': typeof ManagerUsersIdUpdateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/manager'
    | '/logout'
    | '/compliance'
    | '/app/'
    | '/login/'
    | '/manager/'
    | '/compliance/addresses'
    | '/compliance/transactions'
    | '/compliance/alerts'
    | '/compliance/reports'
    | '/api/auth/$'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/compliance/'
    | '/app/account'
    | '/app/books'
    | '/login/error'
    | '/login/verify'
    | '/manager/account'
    | '/manager/books'
    | '/manager/dashboard'
    | '/manager/users'
    | '/compliance/addresses/$address'
    | '/compliance/transactions/$id'
    | '/api/dev/email/$template'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/compliance/addresses/'
    | '/compliance/transactions/'
    | '/app/books/$id'
    | '/manager/books/$id'
    | '/manager/books/new'
    | '/manager/users/$id'
    | '/manager/users/new'
    | '/manager/books/$id/update'
    | '/manager/users/$id/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/app'
    | '/login'
    | '/manager'
    | '/compliance/alerts'
    | '/compliance/reports'
    | '/api/auth/$'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/compliance'
    | '/app/account'
    | '/app/books'
    | '/login/error'
    | '/login/verify'
    | '/manager/account'
    | '/manager/books'
    | '/manager/dashboard'
    | '/manager/users'
    | '/compliance/addresses/$address'
    | '/compliance/transactions/$id'
    | '/api/dev/email/$template'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/compliance/addresses'
    | '/compliance/transactions'
    | '/app/books/$id'
    | '/manager/books/$id'
    | '/manager/books/new'
    | '/manager/users/$id'
    | '/manager/users/new'
    | '/manager/books/$id/update'
    | '/manager/users/$id/update'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/manager'
    | '/_app'
    | '/logout'
    | '/_app/compliance'
    | '/app/'
    | '/login/'
    | '/manager/'
    | '/_app/compliance/addresses'
    | '/_app/compliance/transactions'
    | '/_app/compliance/alerts'
    | '/_app/compliance/reports'
    | '/api/auth/$'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/_app/compliance/'
    | '/app/account/'
    | '/app/books/'
    | '/login/error/'
    | '/login/verify/'
    | '/manager/account/'
    | '/manager/books/'
    | '/manager/dashboard/'
    | '/manager/users/'
    | '/_app/compliance/addresses/$address'
    | '/_app/compliance/transactions/$id'
    | '/api/dev/email/$template'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/_app/compliance/addresses/'
    | '/_app/compliance/transactions/'
    | '/app/books/$id/'
    | '/manager/books/$id/'
    | '/manager/books/new/'
    | '/manager/users/$id/'
    | '/manager/users/new/'
    | '/manager/books/$id/update/'
    | '/manager/users/$id/update/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOpenapiAppRoute: typeof ApiOpenapiAppRouteWithChildren
  ApiOpenapiAuthRoute: typeof ApiOpenapiAuthRouteWithChildren
  ApiRestSplatRoute: typeof ApiRestSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiDevEmailTemplateRoute: typeof ApiDevEmailTemplateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/manager/users/': {
      id: '/manager/users/'
      path: '/users'
      fullPath: '/manager/users'
      preLoaderRoute: typeof ManagerUsersIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/dashboard/': {
      id: '/manager/dashboard/'
      path: '/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/books/': {
      id: '/manager/books/'
      path: '/books'
      fullPath: '/manager/books'
      preLoaderRoute: typeof ManagerBooksIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/account/': {
      id: '/manager/account/'
      path: '/account'
      fullPath: '/manager/account'
      preLoaderRoute: typeof ManagerAccountIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/login/verify/': {
      id: '/login/verify/'
      path: '/verify'
      fullPath: '/login/verify'
      preLoaderRoute: typeof LoginVerifyIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/error/': {
      id: '/login/error/'
      path: '/error'
      fullPath: '/login/error'
      preLoaderRoute: typeof LoginErrorIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/app/books/': {
      id: '/app/books/'
      path: '/books'
      fullPath: '/app/books'
      preLoaderRoute: typeof AppBooksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compliance/': {
      id: '/_app/compliance/'
      path: '/'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AppComplianceIndexRouteImport
      parentRoute: typeof AppComplianceRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rest/$': {
      id: '/api/rest/$'
      path: '/api/rest/$'
      fullPath: '/api/rest/$'
      preLoaderRoute: typeof ApiRestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/auth': {
      id: '/api/openapi/auth'
      path: '/api/openapi/auth'
      fullPath: '/api/openapi/auth'
      preLoaderRoute: typeof ApiOpenapiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/app': {
      id: '/api/openapi/app'
      path: '/api/openapi/app'
      fullPath: '/api/openapi/app'
      preLoaderRoute: typeof ApiOpenapiAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/compliance/reports': {
      id: '/_app/compliance/reports'
      path: '/reports'
      fullPath: '/compliance/reports'
      preLoaderRoute: typeof AppComplianceReportsRouteImport
      parentRoute: typeof AppComplianceRouteRoute
    }
    '/_app/compliance/alerts': {
      id: '/_app/compliance/alerts'
      path: '/alerts'
      fullPath: '/compliance/alerts'
      preLoaderRoute: typeof AppComplianceAlertsRouteImport
      parentRoute: typeof AppComplianceRouteRoute
    }
    '/_app/compliance/transactions': {
      id: '/_app/compliance/transactions'
      path: '/transactions'
      fullPath: '/compliance/transactions'
      preLoaderRoute: typeof AppComplianceTransactionsRouteRouteImport
      parentRoute: typeof AppComplianceRouteRoute
    }
    '/_app/compliance/addresses': {
      id: '/_app/compliance/addresses'
      path: '/addresses'
      fullPath: '/compliance/addresses'
      preLoaderRoute: typeof AppComplianceAddressesRouteRouteImport
      parentRoute: typeof AppComplianceRouteRoute
    }
    '/manager/users/new/': {
      id: '/manager/users/new/'
      path: '/users/new'
      fullPath: '/manager/users/new'
      preLoaderRoute: typeof ManagerUsersNewIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/users/$id/': {
      id: '/manager/users/$id/'
      path: '/users/$id'
      fullPath: '/manager/users/$id'
      preLoaderRoute: typeof ManagerUsersIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/books/new/': {
      id: '/manager/books/new/'
      path: '/books/new'
      fullPath: '/manager/books/new'
      preLoaderRoute: typeof ManagerBooksNewIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/books/$id/': {
      id: '/manager/books/$id/'
      path: '/books/$id'
      fullPath: '/manager/books/$id'
      preLoaderRoute: typeof ManagerBooksIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/app/books/$id/': {
      id: '/app/books/$id/'
      path: '/books/$id'
      fullPath: '/app/books/$id'
      preLoaderRoute: typeof AppBooksIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compliance/transactions/': {
      id: '/_app/compliance/transactions/'
      path: '/'
      fullPath: '/compliance/transactions/'
      preLoaderRoute: typeof AppComplianceTransactionsIndexRouteImport
      parentRoute: typeof AppComplianceTransactionsRouteRoute
    }
    '/_app/compliance/addresses/': {
      id: '/_app/compliance/addresses/'
      path: '/'
      fullPath: '/compliance/addresses/'
      preLoaderRoute: typeof AppComplianceAddressesIndexRouteImport
      parentRoute: typeof AppComplianceAddressesRouteRoute
    }
    '/api/openapi/auth/schema': {
      id: '/api/openapi/auth/schema'
      path: '/schema'
      fullPath: '/api/openapi/auth/schema'
      preLoaderRoute: typeof ApiOpenapiAuthSchemaRouteImport
      parentRoute: typeof ApiOpenapiAuthRoute
    }
    '/api/openapi/app/schema': {
      id: '/api/openapi/app/schema'
      path: '/schema'
      fullPath: '/api/openapi/app/schema'
      preLoaderRoute: typeof ApiOpenapiAppSchemaRouteImport
      parentRoute: typeof ApiOpenapiAppRoute
    }
    '/api/dev/email/$template': {
      id: '/api/dev/email/$template'
      path: '/api/dev/email/$template'
      fullPath: '/api/dev/email/$template'
      preLoaderRoute: typeof ApiDevEmailTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/compliance/transactions/$id': {
      id: '/_app/compliance/transactions/$id'
      path: '/$id'
      fullPath: '/compliance/transactions/$id'
      preLoaderRoute: typeof AppComplianceTransactionsIdRouteImport
      parentRoute: typeof AppComplianceTransactionsRouteRoute
    }
    '/_app/compliance/addresses/$address': {
      id: '/_app/compliance/addresses/$address'
      path: '/$address'
      fullPath: '/compliance/addresses/$address'
      preLoaderRoute: typeof AppComplianceAddressesAddressRouteImport
      parentRoute: typeof AppComplianceAddressesRouteRoute
    }
    '/manager/users/$id/update/': {
      id: '/manager/users/$id/update/'
      path: '/users/$id/update'
      fullPath: '/manager/users/$id/update'
      preLoaderRoute: typeof ManagerUsersIdUpdateIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/books/$id/update/': {
      id: '/manager/books/$id/update/'
      path: '/books/$id/update'
      fullPath: '/manager/books/$id/update'
      preLoaderRoute: typeof ManagerBooksIdUpdateIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppBooksIndexRoute: typeof AppBooksIndexRoute
  AppBooksIdIndexRoute: typeof AppBooksIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppBooksIndexRoute: AppBooksIndexRoute,
  AppBooksIdIndexRoute: AppBooksIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
  LoginErrorIndexRoute: typeof LoginErrorIndexRoute
  LoginVerifyIndexRoute: typeof LoginVerifyIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
  LoginErrorIndexRoute: LoginErrorIndexRoute,
  LoginVerifyIndexRoute: LoginVerifyIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface ManagerRouteRouteChildren {
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerAccountIndexRoute: typeof ManagerAccountIndexRoute
  ManagerBooksIndexRoute: typeof ManagerBooksIndexRoute
  ManagerDashboardIndexRoute: typeof ManagerDashboardIndexRoute
  ManagerUsersIndexRoute: typeof ManagerUsersIndexRoute
  ManagerBooksIdIndexRoute: typeof ManagerBooksIdIndexRoute
  ManagerBooksNewIndexRoute: typeof ManagerBooksNewIndexRoute
  ManagerUsersIdIndexRoute: typeof ManagerUsersIdIndexRoute
  ManagerUsersNewIndexRoute: typeof ManagerUsersNewIndexRoute
  ManagerBooksIdUpdateIndexRoute: typeof ManagerBooksIdUpdateIndexRoute
  ManagerUsersIdUpdateIndexRoute: typeof ManagerUsersIdUpdateIndexRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerAccountIndexRoute: ManagerAccountIndexRoute,
  ManagerBooksIndexRoute: ManagerBooksIndexRoute,
  ManagerDashboardIndexRoute: ManagerDashboardIndexRoute,
  ManagerUsersIndexRoute: ManagerUsersIndexRoute,
  ManagerBooksIdIndexRoute: ManagerBooksIdIndexRoute,
  ManagerBooksNewIndexRoute: ManagerBooksNewIndexRoute,
  ManagerUsersIdIndexRoute: ManagerUsersIdIndexRoute,
  ManagerUsersNewIndexRoute: ManagerUsersNewIndexRoute,
  ManagerBooksIdUpdateIndexRoute: ManagerBooksIdUpdateIndexRoute,
  ManagerUsersIdUpdateIndexRoute: ManagerUsersIdUpdateIndexRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

interface AppComplianceAddressesRouteRouteChildren {
  AppComplianceAddressesAddressRoute: typeof AppComplianceAddressesAddressRoute
  AppComplianceAddressesIndexRoute: typeof AppComplianceAddressesIndexRoute
}

const AppComplianceAddressesRouteRouteChildren: AppComplianceAddressesRouteRouteChildren =
  {
    AppComplianceAddressesAddressRoute: AppComplianceAddressesAddressRoute,
    AppComplianceAddressesIndexRoute: AppComplianceAddressesIndexRoute,
  }

const AppComplianceAddressesRouteRouteWithChildren =
  AppComplianceAddressesRouteRoute._addFileChildren(
    AppComplianceAddressesRouteRouteChildren,
  )

interface AppComplianceTransactionsRouteRouteChildren {
  AppComplianceTransactionsIdRoute: typeof AppComplianceTransactionsIdRoute
  AppComplianceTransactionsIndexRoute: typeof AppComplianceTransactionsIndexRoute
}

const AppComplianceTransactionsRouteRouteChildren: AppComplianceTransactionsRouteRouteChildren =
  {
    AppComplianceTransactionsIdRoute: AppComplianceTransactionsIdRoute,
    AppComplianceTransactionsIndexRoute: AppComplianceTransactionsIndexRoute,
  }

const AppComplianceTransactionsRouteRouteWithChildren =
  AppComplianceTransactionsRouteRoute._addFileChildren(
    AppComplianceTransactionsRouteRouteChildren,
  )

interface AppComplianceRouteRouteChildren {
  AppComplianceAddressesRouteRoute: typeof AppComplianceAddressesRouteRouteWithChildren
  AppComplianceTransactionsRouteRoute: typeof AppComplianceTransactionsRouteRouteWithChildren
  AppComplianceAlertsRoute: typeof AppComplianceAlertsRoute
  AppComplianceReportsRoute: typeof AppComplianceReportsRoute
  AppComplianceIndexRoute: typeof AppComplianceIndexRoute
}

const AppComplianceRouteRouteChildren: AppComplianceRouteRouteChildren = {
  AppComplianceAddressesRouteRoute:
    AppComplianceAddressesRouteRouteWithChildren,
  AppComplianceTransactionsRouteRoute:
    AppComplianceTransactionsRouteRouteWithChildren,
  AppComplianceAlertsRoute: AppComplianceAlertsRoute,
  AppComplianceReportsRoute: AppComplianceReportsRoute,
  AppComplianceIndexRoute: AppComplianceIndexRoute,
}

const AppComplianceRouteRouteWithChildren =
  AppComplianceRouteRoute._addFileChildren(AppComplianceRouteRouteChildren)

interface AppRouteChildren {
  AppComplianceRouteRoute: typeof AppComplianceRouteRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppComplianceRouteRoute: AppComplianceRouteRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiOpenapiAppRouteChildren {
  ApiOpenapiAppSchemaRoute: typeof ApiOpenapiAppSchemaRoute
}

const ApiOpenapiAppRouteChildren: ApiOpenapiAppRouteChildren = {
  ApiOpenapiAppSchemaRoute: ApiOpenapiAppSchemaRoute,
}

const ApiOpenapiAppRouteWithChildren = ApiOpenapiAppRoute._addFileChildren(
  ApiOpenapiAppRouteChildren,
)

interface ApiOpenapiAuthRouteChildren {
  ApiOpenapiAuthSchemaRoute: typeof ApiOpenapiAuthSchemaRoute
}

const ApiOpenapiAuthRouteChildren: ApiOpenapiAuthRouteChildren = {
  ApiOpenapiAuthSchemaRoute: ApiOpenapiAuthSchemaRoute,
}

const ApiOpenapiAuthRouteWithChildren = ApiOpenapiAuthRoute._addFileChildren(
  ApiOpenapiAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOpenapiAppRoute: ApiOpenapiAppRouteWithChildren,
  ApiOpenapiAuthRoute: ApiOpenapiAuthRouteWithChildren,
  ApiRestSplatRoute: ApiRestSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiDevEmailTemplateRoute: ApiDevEmailTemplateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
