/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignUpRouteRouteImport } from './routes/sign-up/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as ForgotPasswordRouteRouteImport } from './routes/forgot-password/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppVaultsRouteRouteImport } from './routes/_app/vaults/route'
import { Route as AppSignersRouteRouteImport } from './routes/_app/signers/route'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppPoliciesRouteRouteImport } from './routes/_app/policies/route'
import { Route as AppOperationsRouteRouteImport } from './routes/_app/operations/route'
import { Route as AppIdentitiesRouteRouteImport } from './routes/_app/identities/route'
import { Route as AppComplianceRouteRouteImport } from './routes/_app/compliance/route'
import { Route as AppAddressBookRouteRouteImport } from './routes/_app/address-book/route'
import { Route as AppAccountRouteRouteImport } from './routes/_app/account/route'
import { Route as LoginVerifyIndexRouteImport } from './routes/login/verify.index'
import { Route as LoginErrorIndexRouteImport } from './routes/login/error.index'
import { Route as AppVaultsIndexRouteImport } from './routes/_app/vaults/index'
import { Route as AppSignersIndexRouteImport } from './routes/_app/signers/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppIdentitiesIndexRouteImport } from './routes/_app/identities/index'
import { Route as AppComplianceIndexRouteImport } from './routes/_app/compliance/index'
import { Route as AppAddressBookIndexRouteImport } from './routes/_app/address-book/index'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiRestSplatRouteImport } from './routes/api/rest.$'
import { Route as ApiOpenapiAuthRouteImport } from './routes/api/openapi/auth'
import { Route as ApiOpenapiAppRouteImport } from './routes/api/openapi/app'
import { Route as AppVaultsTabsRouteImport } from './routes/_app/vaults/tabs'
import { Route as AppVaultsNewRouteImport } from './routes/_app/vaults/new'
import { Route as AppVaultsLayoutsRouteImport } from './routes/_app/vaults/layouts'
import { Route as AppSignersNewRouteImport } from './routes/_app/signers/new'
import { Route as AppSettingsWorkspacesRouteImport } from './routes/_app/settings/workspaces'
import { Route as AppSettingsRolesRouteImport } from './routes/_app/settings/roles'
import { Route as AppSettingsMembersRouteImport } from './routes/_app/settings/members'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings/billing'
import { Route as AppSettingsBackupsRouteImport } from './routes/_app/settings/backups'
import { Route as AppSettingsAuditRouteImport } from './routes/_app/settings/audit'
import { Route as AppIdentitiesNewRouteImport } from './routes/_app/identities/new'
import { Route as AppComplianceReportsRouteImport } from './routes/_app/compliance/reports'
import { Route as AppComplianceAlertsRouteImport } from './routes/_app/compliance/alerts'
import { Route as AppAccountSecurityRouteImport } from './routes/_app/account/security'
import { Route as AppVaultsVaultIdRouteRouteImport } from './routes/_app/vaults/$vaultId/route'
import { Route as AppSignersSignerIdRouteRouteImport } from './routes/_app/signers/$signerId/route'
import { Route as AppSettingsTeamsRouteRouteImport } from './routes/_app/settings/teams/route'
import { Route as AppPoliciesWhitelistsRouteRouteImport } from './routes/_app/policies/whitelists/route'
import { Route as AppPoliciesTransactionsRouteRouteImport } from './routes/_app/policies/transactions/route'
import { Route as AppOperationsOperationIdRouteRouteImport } from './routes/_app/operations/$operationId/route'
import { Route as AppIdentitiesIdentityIdRouteRouteImport } from './routes/_app/identities/$identityId/route'
import { Route as AppComplianceTransactionsRouteRouteImport } from './routes/_app/compliance/transactions/route'
import { Route as AppComplianceAddressesRouteRouteImport } from './routes/_app/compliance/addresses/route'
import { Route as AppVaultsVaultIdIndexRouteImport } from './routes/_app/vaults/$vaultId/index'
import { Route as AppSignersSignerIdIndexRouteImport } from './routes/_app/signers/$signerId/index'
import { Route as AppSettingsTeamsIndexRouteImport } from './routes/_app/settings/teams/index'
import { Route as AppSettingsGovernanceIndexRouteImport } from './routes/_app/settings/governance/index'
import { Route as AppPoliciesWhitelistsIndexRouteImport } from './routes/_app/policies/whitelists/index'
import { Route as AppPoliciesTransactionsIndexRouteImport } from './routes/_app/policies/transactions/index'
import { Route as AppIdentitiesIdentityIdIndexRouteImport } from './routes/_app/identities/$identityId/index'
import { Route as AppComplianceTransactionsIndexRouteImport } from './routes/_app/compliance/transactions/index'
import { Route as AppComplianceAddressesIndexRouteImport } from './routes/_app/compliance/addresses/index'
import { Route as ApiOpenapiAppSchemaRouteImport } from './routes/api/openapi/app.schema'
import { Route as ApiDevEmailTemplateRouteImport } from './routes/api/dev.email.$template'
import { Route as AppVaultsVaultIdEditRouteImport } from './routes/_app/vaults/$vaultId/edit'
import { Route as AppSettingsTeamsTeamIdRouteImport } from './routes/_app/settings/teams/$teamId'
import { Route as AppSettingsGovernancePendingRouteImport } from './routes/_app/settings/governance/pending'
import { Route as AppPoliciesWhitelistsNewRouteImport } from './routes/_app/policies/whitelists/new'
import { Route as AppIdentitiesIdentityIdEditRouteImport } from './routes/_app/identities/$identityId/edit'
import { Route as AppComplianceTransactionsIdRouteImport } from './routes/_app/compliance/transactions/$id'
import { Route as AppComplianceAddressesAddressRouteImport } from './routes/_app/compliance/addresses/$address'
import { Route as AppVaultsVaultIdAddressesRouteRouteImport } from './routes/_app/vaults/$vaultId/addresses/route'
import { Route as AppPoliciesWhitelistsWhitelistIdRouteRouteImport } from './routes/_app/policies/whitelists/$whitelistId/route'
import { Route as AppPoliciesTransactionsPolicyIdRouteRouteImport } from './routes/_app/policies/transactions/$policyId/route'
import { Route as AppVaultsVaultIdAddressesIndexRouteImport } from './routes/_app/vaults/$vaultId/addresses/index'
import { Route as AppPoliciesWhitelistsWhitelistIdIndexRouteImport } from './routes/_app/policies/whitelists/$whitelistId/index'
import { Route as AppPoliciesTransactionsPolicyIdIndexRouteImport } from './routes/_app/policies/transactions/$policyId/index'
import { Route as AppVaultsVaultIdResharesReshareIdRouteImport } from './routes/_app/vaults/$vaultId/reshares/$reshareId'
import { Route as AppVaultsVaultIdAddressesNewRouteImport } from './routes/_app/vaults/$vaultId/addresses/new'
import { Route as AppPoliciesWhitelistsWhitelistIdEditRouteImport } from './routes/_app/policies/whitelists/$whitelistId/edit'
import { Route as AppVaultsVaultIdAddressesAddressIdRouteRouteImport } from './routes/_app/vaults/$vaultId/addresses/$addressId/route'
import { Route as AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteImport } from './routes/_app/policies/whitelists/$whitelistId/versions/route'
import { Route as AppPoliciesTransactionsPolicyIdVersionsRouteRouteImport } from './routes/_app/policies/transactions/$policyId/versions/route'
import { Route as AppVaultsVaultIdAddressesAddressIdIndexRouteImport } from './routes/_app/vaults/$vaultId/addresses/$addressId/index'
import { Route as AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteImport } from './routes/_app/policies/whitelists/$whitelistId/versions/$versionNumber/route'
import { Route as AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteImport } from './routes/_app/policies/transactions/$policyId/versions/$versionNumber/route'
import { Route as AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberIndexRouteImport } from './routes/_app/policies/whitelists/$whitelistId/versions/$versionNumber/index'
import { Route as AppPoliciesTransactionsPolicyIdVersionsVersionNumberIndexRouteImport } from './routes/_app/policies/transactions/$policyId/versions/$versionNumber/index'
import { Route as AppVaultsVaultIdChainChainAddressesAddressRouteRouteImport } from './routes/_app/vaults/$vaultId/chain/$chain/addresses/$address/route'
import { Route as AppVaultsVaultIdChainChainAddressesAddressIndexRouteImport } from './routes/_app/vaults/$vaultId/chain/$chain/addresses/$address/index'
import { Route as AppVaultsVaultIdChainChainAddressesAddressTransferRouteImport } from './routes/_app/vaults/$vaultId/chain/$chain/addresses/$address/transfer'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRouteRoute = SignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRouteRoute = ForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignUpRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForgotPasswordRouteRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultsRouteRoute = AppVaultsRouteRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => AppRoute,
} as any)
const AppSignersRouteRoute = AppSignersRouteRouteImport.update({
  id: '/signers',
  path: '/signers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesRouteRoute = AppPoliciesRouteRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsRouteRoute = AppOperationsRouteRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentitiesRouteRoute = AppIdentitiesRouteRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRouteRoute = AppComplianceRouteRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppAddressBookRouteRoute = AppAddressBookRouteRouteImport.update({
  id: '/address-book',
  path: '/address-book',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRouteRoute = AppAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const LoginVerifyIndexRoute = LoginVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginErrorIndexRoute = LoginErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppVaultsIndexRoute = AppVaultsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVaultsRouteRoute,
} as any)
const AppSignersIndexRoute = AppSignersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSignersRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppIdentitiesIndexRoute = AppIdentitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIdentitiesRouteRoute,
} as any)
const AppComplianceIndexRoute = AppComplianceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppComplianceRouteRoute,
} as any)
const AppAddressBookIndexRoute = AppAddressBookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAddressBookRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestSplatRoute = ApiRestSplatRouteImport.update({
  id: '/api/rest/$',
  path: '/api/rest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiAuthRoute = ApiOpenapiAuthRouteImport.update({
  id: '/api/openapi/auth',
  path: '/api/openapi/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiAppRoute = ApiOpenapiAppRouteImport.update({
  id: '/api/openapi/app',
  path: '/api/openapi/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultsTabsRoute = AppVaultsTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => AppVaultsRouteRoute,
} as any)
const AppVaultsNewRoute = AppVaultsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppVaultsRouteRoute,
} as any)
const AppVaultsLayoutsRoute = AppVaultsLayoutsRouteImport.update({
  id: '/layouts',
  path: '/layouts',
  getParentRoute: () => AppVaultsRouteRoute,
} as any)
const AppSignersNewRoute = AppSignersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSignersRouteRoute,
} as any)
const AppSettingsWorkspacesRoute = AppSettingsWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsBackupsRoute = AppSettingsBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppIdentitiesNewRoute = AppIdentitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppIdentitiesRouteRoute,
} as any)
const AppComplianceReportsRoute = AppComplianceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppComplianceRouteRoute,
} as any)
const AppComplianceAlertsRoute = AppComplianceAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppComplianceRouteRoute,
} as any)
const AppAccountSecurityRoute = AppAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppVaultsVaultIdRouteRoute = AppVaultsVaultIdRouteRouteImport.update({
  id: '/$vaultId',
  path: '/$vaultId',
  getParentRoute: () => AppVaultsRouteRoute,
} as any)
const AppSignersSignerIdRouteRoute = AppSignersSignerIdRouteRouteImport.update({
  id: '/$signerId',
  path: '/$signerId',
  getParentRoute: () => AppSignersRouteRoute,
} as any)
const AppSettingsTeamsRouteRoute = AppSettingsTeamsRouteRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppPoliciesWhitelistsRouteRoute =
  AppPoliciesWhitelistsRouteRouteImport.update({
    id: '/whitelists',
    path: '/whitelists',
    getParentRoute: () => AppPoliciesRouteRoute,
  } as any)
const AppPoliciesTransactionsRouteRoute =
  AppPoliciesTransactionsRouteRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AppPoliciesRouteRoute,
  } as any)
const AppOperationsOperationIdRouteRoute =
  AppOperationsOperationIdRouteRouteImport.update({
    id: '/$operationId',
    path: '/$operationId',
    getParentRoute: () => AppOperationsRouteRoute,
  } as any)
const AppIdentitiesIdentityIdRouteRoute =
  AppIdentitiesIdentityIdRouteRouteImport.update({
    id: '/$identityId',
    path: '/$identityId',
    getParentRoute: () => AppIdentitiesRouteRoute,
  } as any)
const AppComplianceTransactionsRouteRoute =
  AppComplianceTransactionsRouteRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AppComplianceRouteRoute,
  } as any)
const AppComplianceAddressesRouteRoute =
  AppComplianceAddressesRouteRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AppComplianceRouteRoute,
  } as any)
const AppVaultsVaultIdIndexRoute = AppVaultsVaultIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVaultsVaultIdRouteRoute,
} as any)
const AppSignersSignerIdIndexRoute = AppSignersSignerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSignersSignerIdRouteRoute,
} as any)
const AppSettingsTeamsIndexRoute = AppSettingsTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsTeamsRouteRoute,
} as any)
const AppSettingsGovernanceIndexRoute =
  AppSettingsGovernanceIndexRouteImport.update({
    id: '/governance/',
    path: '/governance/',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppPoliciesWhitelistsIndexRoute =
  AppPoliciesWhitelistsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPoliciesWhitelistsRouteRoute,
  } as any)
const AppPoliciesTransactionsIndexRoute =
  AppPoliciesTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPoliciesTransactionsRouteRoute,
  } as any)
const AppIdentitiesIdentityIdIndexRoute =
  AppIdentitiesIdentityIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppIdentitiesIdentityIdRouteRoute,
  } as any)
const AppComplianceTransactionsIndexRoute =
  AppComplianceTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppComplianceTransactionsRouteRoute,
  } as any)
const AppComplianceAddressesIndexRoute =
  AppComplianceAddressesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppComplianceAddressesRouteRoute,
  } as any)
const ApiOpenapiAppSchemaRoute = ApiOpenapiAppSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ApiOpenapiAppRoute,
} as any)
const ApiDevEmailTemplateRoute = ApiDevEmailTemplateRouteImport.update({
  id: '/api/dev/email/$template',
  path: '/api/dev/email/$template',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultsVaultIdEditRoute = AppVaultsVaultIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppVaultsVaultIdRouteRoute,
} as any)
const AppSettingsTeamsTeamIdRoute = AppSettingsTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => AppSettingsTeamsRouteRoute,
} as any)
const AppSettingsGovernancePendingRoute =
  AppSettingsGovernancePendingRouteImport.update({
    id: '/governance/pending',
    path: '/governance/pending',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppPoliciesWhitelistsNewRoute =
  AppPoliciesWhitelistsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppPoliciesWhitelistsRouteRoute,
  } as any)
const AppIdentitiesIdentityIdEditRoute =
  AppIdentitiesIdentityIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppIdentitiesIdentityIdRouteRoute,
  } as any)
const AppComplianceTransactionsIdRoute =
  AppComplianceTransactionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppComplianceTransactionsRouteRoute,
  } as any)
const AppComplianceAddressesAddressRoute =
  AppComplianceAddressesAddressRouteImport.update({
    id: '/$address',
    path: '/$address',
    getParentRoute: () => AppComplianceAddressesRouteRoute,
  } as any)
const AppVaultsVaultIdAddressesRouteRoute =
  AppVaultsVaultIdAddressesRouteRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AppVaultsVaultIdRouteRoute,
  } as any)
const AppPoliciesWhitelistsWhitelistIdRouteRoute =
  AppPoliciesWhitelistsWhitelistIdRouteRouteImport.update({
    id: '/$whitelistId',
    path: '/$whitelistId',
    getParentRoute: () => AppPoliciesWhitelistsRouteRoute,
  } as any)
const AppPoliciesTransactionsPolicyIdRouteRoute =
  AppPoliciesTransactionsPolicyIdRouteRouteImport.update({
    id: '/$policyId',
    path: '/$policyId',
    getParentRoute: () => AppPoliciesTransactionsRouteRoute,
  } as any)
const AppVaultsVaultIdAddressesIndexRoute =
  AppVaultsVaultIdAddressesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppVaultsVaultIdAddressesRouteRoute,
  } as any)
const AppPoliciesWhitelistsWhitelistIdIndexRoute =
  AppPoliciesWhitelistsWhitelistIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPoliciesWhitelistsWhitelistIdRouteRoute,
  } as any)
const AppPoliciesTransactionsPolicyIdIndexRoute =
  AppPoliciesTransactionsPolicyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPoliciesTransactionsPolicyIdRouteRoute,
  } as any)
const AppVaultsVaultIdResharesReshareIdRoute =
  AppVaultsVaultIdResharesReshareIdRouteImport.update({
    id: '/reshares/$reshareId',
    path: '/reshares/$reshareId',
    getParentRoute: () => AppVaultsVaultIdRouteRoute,
  } as any)
const AppVaultsVaultIdAddressesNewRoute =
  AppVaultsVaultIdAddressesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppVaultsVaultIdAddressesRouteRoute,
  } as any)
const AppPoliciesWhitelistsWhitelistIdEditRoute =
  AppPoliciesWhitelistsWhitelistIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppPoliciesWhitelistsWhitelistIdRouteRoute,
  } as any)
const AppVaultsVaultIdAddressesAddressIdRouteRoute =
  AppVaultsVaultIdAddressesAddressIdRouteRouteImport.update({
    id: '/$addressId',
    path: '/$addressId',
    getParentRoute: () => AppVaultsVaultIdAddressesRouteRoute,
  } as any)
const AppPoliciesWhitelistsWhitelistIdVersionsRouteRoute =
  AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AppPoliciesWhitelistsWhitelistIdRouteRoute,
  } as any)
const AppPoliciesTransactionsPolicyIdVersionsRouteRoute =
  AppPoliciesTransactionsPolicyIdVersionsRouteRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AppPoliciesTransactionsPolicyIdRouteRoute,
  } as any)
const AppVaultsVaultIdAddressesAddressIdIndexRoute =
  AppVaultsVaultIdAddressesAddressIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppVaultsVaultIdAddressesAddressIdRouteRoute,
  } as any)
const AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRoute =
  AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteImport.update({
    id: '/$versionNumber',
    path: '/$versionNumber',
    getParentRoute: () => AppPoliciesWhitelistsWhitelistIdVersionsRouteRoute,
  } as any)
const AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRoute =
  AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteImport.update({
    id: '/$versionNumber',
    path: '/$versionNumber',
    getParentRoute: () => AppPoliciesTransactionsPolicyIdVersionsRouteRoute,
  } as any)
const AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberIndexRoute =
  AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRoute,
  } as any)
const AppPoliciesTransactionsPolicyIdVersionsVersionNumberIndexRoute =
  AppPoliciesTransactionsPolicyIdVersionsVersionNumberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRoute,
  } as any)
const AppVaultsVaultIdChainChainAddressesAddressRouteRoute =
  AppVaultsVaultIdChainChainAddressesAddressRouteRouteImport.update({
    id: '/chain/$chain/addresses/$address',
    path: '/chain/$chain/addresses/$address',
    getParentRoute: () => AppVaultsVaultIdRouteRoute,
  } as any)
const AppVaultsVaultIdChainChainAddressesAddressIndexRoute =
  AppVaultsVaultIdChainChainAddressesAddressIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppVaultsVaultIdChainChainAddressesAddressRouteRoute,
  } as any)
const AppVaultsVaultIdChainChainAddressesAddressTransferRoute =
  AppVaultsVaultIdChainChainAddressesAddressTransferRouteImport.update({
    id: '/transfer',
    path: '/transfer',
    getParentRoute: () => AppVaultsVaultIdChainChainAddressesAddressRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/sign-up': typeof SignUpRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/account': typeof AppAccountRouteRouteWithChildren
  '/address-book': typeof AppAddressBookRouteRouteWithChildren
  '/compliance': typeof AppComplianceRouteRouteWithChildren
  '/identities': typeof AppIdentitiesRouteRouteWithChildren
  '/operations': typeof AppOperationsRouteRouteWithChildren
  '/policies': typeof AppPoliciesRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/signers': typeof AppSignersRouteRouteWithChildren
  '/vaults': typeof AppVaultsRouteRouteWithChildren
  '/overview': typeof AppOverviewRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/compliance/addresses': typeof AppComplianceAddressesRouteRouteWithChildren
  '/compliance/transactions': typeof AppComplianceTransactionsRouteRouteWithChildren
  '/identities/$identityId': typeof AppIdentitiesIdentityIdRouteRouteWithChildren
  '/operations/$operationId': typeof AppOperationsOperationIdRouteRoute
  '/policies/transactions': typeof AppPoliciesTransactionsRouteRouteWithChildren
  '/policies/whitelists': typeof AppPoliciesWhitelistsRouteRouteWithChildren
  '/settings/teams': typeof AppSettingsTeamsRouteRouteWithChildren
  '/signers/$signerId': typeof AppSignersSignerIdRouteRouteWithChildren
  '/vaults/$vaultId': typeof AppVaultsVaultIdRouteRouteWithChildren
  '/account/security': typeof AppAccountSecurityRoute
  '/compliance/alerts': typeof AppComplianceAlertsRoute
  '/compliance/reports': typeof AppComplianceReportsRoute
  '/identities/new': typeof AppIdentitiesNewRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/backups': typeof AppSettingsBackupsRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/workspaces': typeof AppSettingsWorkspacesRoute
  '/signers/new': typeof AppSignersNewRoute
  '/vaults/layouts': typeof AppVaultsLayoutsRoute
  '/vaults/new': typeof AppVaultsNewRoute
  '/vaults/tabs': typeof AppVaultsTabsRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRoute
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/account/': typeof AppAccountIndexRoute
  '/address-book/': typeof AppAddressBookIndexRoute
  '/compliance/': typeof AppComplianceIndexRoute
  '/identities/': typeof AppIdentitiesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/signers/': typeof AppSignersIndexRoute
  '/vaults/': typeof AppVaultsIndexRoute
  '/login/error': typeof LoginErrorIndexRoute
  '/login/verify': typeof LoginVerifyIndexRoute
  '/policies/transactions/$policyId': typeof AppPoliciesTransactionsPolicyIdRouteRouteWithChildren
  '/policies/whitelists/$whitelistId': typeof AppPoliciesWhitelistsWhitelistIdRouteRouteWithChildren
  '/vaults/$vaultId/addresses': typeof AppVaultsVaultIdAddressesRouteRouteWithChildren
  '/compliance/addresses/$address': typeof AppComplianceAddressesAddressRoute
  '/compliance/transactions/$id': typeof AppComplianceTransactionsIdRoute
  '/identities/$identityId/edit': typeof AppIdentitiesIdentityIdEditRoute
  '/policies/whitelists/new': typeof AppPoliciesWhitelistsNewRoute
  '/settings/governance/pending': typeof AppSettingsGovernancePendingRoute
  '/settings/teams/$teamId': typeof AppSettingsTeamsTeamIdRoute
  '/vaults/$vaultId/edit': typeof AppVaultsVaultIdEditRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/compliance/addresses/': typeof AppComplianceAddressesIndexRoute
  '/compliance/transactions/': typeof AppComplianceTransactionsIndexRoute
  '/identities/$identityId/': typeof AppIdentitiesIdentityIdIndexRoute
  '/policies/transactions/': typeof AppPoliciesTransactionsIndexRoute
  '/policies/whitelists/': typeof AppPoliciesWhitelistsIndexRoute
  '/settings/governance': typeof AppSettingsGovernanceIndexRoute
  '/settings/teams/': typeof AppSettingsTeamsIndexRoute
  '/signers/$signerId/': typeof AppSignersSignerIdIndexRoute
  '/vaults/$vaultId/': typeof AppVaultsVaultIdIndexRoute
  '/policies/transactions/$policyId/versions': typeof AppPoliciesTransactionsPolicyIdVersionsRouteRouteWithChildren
  '/policies/whitelists/$whitelistId/versions': typeof AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteWithChildren
  '/vaults/$vaultId/addresses/$addressId': typeof AppVaultsVaultIdAddressesAddressIdRouteRouteWithChildren
  '/policies/whitelists/$whitelistId/edit': typeof AppPoliciesWhitelistsWhitelistIdEditRoute
  '/vaults/$vaultId/addresses/new': typeof AppVaultsVaultIdAddressesNewRoute
  '/vaults/$vaultId/reshares/$reshareId': typeof AppVaultsVaultIdResharesReshareIdRoute
  '/policies/transactions/$policyId/': typeof AppPoliciesTransactionsPolicyIdIndexRoute
  '/policies/whitelists/$whitelistId/': typeof AppPoliciesWhitelistsWhitelistIdIndexRoute
  '/vaults/$vaultId/addresses/': typeof AppVaultsVaultIdAddressesIndexRoute
  '/policies/transactions/$policyId/versions/$versionNumber': typeof AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteWithChildren
  '/policies/whitelists/$whitelistId/versions/$versionNumber': typeof AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteWithChildren
  '/vaults/$vaultId/addresses/$addressId/': typeof AppVaultsVaultIdAddressesAddressIdIndexRoute
  '/vaults/$vaultId/chain/$chain/addresses/$address': typeof AppVaultsVaultIdChainChainAddressesAddressRouteRouteWithChildren
  '/policies/transactions/$policyId/versions/$versionNumber/': typeof AppPoliciesTransactionsPolicyIdVersionsVersionNumberIndexRoute
  '/policies/whitelists/$whitelistId/versions/$versionNumber/': typeof AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberIndexRoute
  '/vaults/$vaultId/chain/$chain/addresses/$address/transfer': typeof AppVaultsVaultIdChainChainAddressesAddressTransferRoute
  '/vaults/$vaultId/chain/$chain/addresses/$address/': typeof AppVaultsVaultIdChainChainAddressesAddressIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/operations': typeof AppOperationsRouteRouteWithChildren
  '/policies': typeof AppPoliciesRouteRouteWithChildren
  '/overview': typeof AppOverviewRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/operations/$operationId': typeof AppOperationsOperationIdRouteRoute
  '/account/security': typeof AppAccountSecurityRoute
  '/compliance/alerts': typeof AppComplianceAlertsRoute
  '/compliance/reports': typeof AppComplianceReportsRoute
  '/identities/new': typeof AppIdentitiesNewRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/backups': typeof AppSettingsBackupsRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/workspaces': typeof AppSettingsWorkspacesRoute
  '/signers/new': typeof AppSignersNewRoute
  '/vaults/layouts': typeof AppVaultsLayoutsRoute
  '/vaults/new': typeof AppVaultsNewRoute
  '/vaults/tabs': typeof AppVaultsTabsRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRoute
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/account': typeof AppAccountIndexRoute
  '/address-book': typeof AppAddressBookIndexRoute
  '/compliance': typeof AppComplianceIndexRoute
  '/identities': typeof AppIdentitiesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/signers': typeof AppSignersIndexRoute
  '/vaults': typeof AppVaultsIndexRoute
  '/login/error': typeof LoginErrorIndexRoute
  '/login/verify': typeof LoginVerifyIndexRoute
  '/compliance/addresses/$address': typeof AppComplianceAddressesAddressRoute
  '/compliance/transactions/$id': typeof AppComplianceTransactionsIdRoute
  '/identities/$identityId/edit': typeof AppIdentitiesIdentityIdEditRoute
  '/policies/whitelists/new': typeof AppPoliciesWhitelistsNewRoute
  '/settings/governance/pending': typeof AppSettingsGovernancePendingRoute
  '/settings/teams/$teamId': typeof AppSettingsTeamsTeamIdRoute
  '/vaults/$vaultId/edit': typeof AppVaultsVaultIdEditRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/compliance/addresses': typeof AppComplianceAddressesIndexRoute
  '/compliance/transactions': typeof AppComplianceTransactionsIndexRoute
  '/identities/$identityId': typeof AppIdentitiesIdentityIdIndexRoute
  '/policies/transactions': typeof AppPoliciesTransactionsIndexRoute
  '/policies/whitelists': typeof AppPoliciesWhitelistsIndexRoute
  '/settings/governance': typeof AppSettingsGovernanceIndexRoute
  '/settings/teams': typeof AppSettingsTeamsIndexRoute
  '/signers/$signerId': typeof AppSignersSignerIdIndexRoute
  '/vaults/$vaultId': typeof AppVaultsVaultIdIndexRoute
  '/policies/transactions/$policyId/versions': typeof AppPoliciesTransactionsPolicyIdVersionsRouteRouteWithChildren
  '/policies/whitelists/$whitelistId/versions': typeof AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteWithChildren
  '/policies/whitelists/$whitelistId/edit': typeof AppPoliciesWhitelistsWhitelistIdEditRoute
  '/vaults/$vaultId/addresses/new': typeof AppVaultsVaultIdAddressesNewRoute
  '/vaults/$vaultId/reshares/$reshareId': typeof AppVaultsVaultIdResharesReshareIdRoute
  '/policies/transactions/$policyId': typeof AppPoliciesTransactionsPolicyIdIndexRoute
  '/policies/whitelists/$whitelistId': typeof AppPoliciesWhitelistsWhitelistIdIndexRoute
  '/vaults/$vaultId/addresses': typeof AppVaultsVaultIdAddressesIndexRoute
  '/vaults/$vaultId/addresses/$addressId': typeof AppVaultsVaultIdAddressesAddressIdIndexRoute
  '/policies/transactions/$policyId/versions/$versionNumber': typeof AppPoliciesTransactionsPolicyIdVersionsVersionNumberIndexRoute
  '/policies/whitelists/$whitelistId/versions/$versionNumber': typeof AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberIndexRoute
  '/vaults/$vaultId/chain/$chain/addresses/$address/transfer': typeof AppVaultsVaultIdChainChainAddressesAddressTransferRoute
  '/vaults/$vaultId/chain/$chain/addresses/$address': typeof AppVaultsVaultIdChainChainAddressesAddressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/sign-up': typeof SignUpRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_app/account': typeof AppAccountRouteRouteWithChildren
  '/_app/address-book': typeof AppAddressBookRouteRouteWithChildren
  '/_app/compliance': typeof AppComplianceRouteRouteWithChildren
  '/_app/identities': typeof AppIdentitiesRouteRouteWithChildren
  '/_app/operations': typeof AppOperationsRouteRouteWithChildren
  '/_app/policies': typeof AppPoliciesRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/signers': typeof AppSignersRouteRouteWithChildren
  '/_app/vaults': typeof AppVaultsRouteRouteWithChildren
  '/_app/overview': typeof AppOverviewRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/_app/compliance/addresses': typeof AppComplianceAddressesRouteRouteWithChildren
  '/_app/compliance/transactions': typeof AppComplianceTransactionsRouteRouteWithChildren
  '/_app/identities/$identityId': typeof AppIdentitiesIdentityIdRouteRouteWithChildren
  '/_app/operations/$operationId': typeof AppOperationsOperationIdRouteRoute
  '/_app/policies/transactions': typeof AppPoliciesTransactionsRouteRouteWithChildren
  '/_app/policies/whitelists': typeof AppPoliciesWhitelistsRouteRouteWithChildren
  '/_app/settings/teams': typeof AppSettingsTeamsRouteRouteWithChildren
  '/_app/signers/$signerId': typeof AppSignersSignerIdRouteRouteWithChildren
  '/_app/vaults/$vaultId': typeof AppVaultsVaultIdRouteRouteWithChildren
  '/_app/account/security': typeof AppAccountSecurityRoute
  '/_app/compliance/alerts': typeof AppComplianceAlertsRoute
  '/_app/compliance/reports': typeof AppComplianceReportsRoute
  '/_app/identities/new': typeof AppIdentitiesNewRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/backups': typeof AppSettingsBackupsRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/workspaces': typeof AppSettingsWorkspacesRoute
  '/_app/signers/new': typeof AppSignersNewRoute
  '/_app/vaults/layouts': typeof AppVaultsLayoutsRoute
  '/_app/vaults/new': typeof AppVaultsNewRoute
  '/_app/vaults/tabs': typeof AppVaultsTabsRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRoute
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/address-book/': typeof AppAddressBookIndexRoute
  '/_app/compliance/': typeof AppComplianceIndexRoute
  '/_app/identities/': typeof AppIdentitiesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/signers/': typeof AppSignersIndexRoute
  '/_app/vaults/': typeof AppVaultsIndexRoute
  '/login/error/': typeof LoginErrorIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/_app/policies/transactions/$policyId': typeof AppPoliciesTransactionsPolicyIdRouteRouteWithChildren
  '/_app/policies/whitelists/$whitelistId': typeof AppPoliciesWhitelistsWhitelistIdRouteRouteWithChildren
  '/_app/vaults/$vaultId/addresses': typeof AppVaultsVaultIdAddressesRouteRouteWithChildren
  '/_app/compliance/addresses/$address': typeof AppComplianceAddressesAddressRoute
  '/_app/compliance/transactions/$id': typeof AppComplianceTransactionsIdRoute
  '/_app/identities/$identityId/edit': typeof AppIdentitiesIdentityIdEditRoute
  '/_app/policies/whitelists/new': typeof AppPoliciesWhitelistsNewRoute
  '/_app/settings/governance/pending': typeof AppSettingsGovernancePendingRoute
  '/_app/settings/teams/$teamId': typeof AppSettingsTeamsTeamIdRoute
  '/_app/vaults/$vaultId/edit': typeof AppVaultsVaultIdEditRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/_app/compliance/addresses/': typeof AppComplianceAddressesIndexRoute
  '/_app/compliance/transactions/': typeof AppComplianceTransactionsIndexRoute
  '/_app/identities/$identityId/': typeof AppIdentitiesIdentityIdIndexRoute
  '/_app/policies/transactions/': typeof AppPoliciesTransactionsIndexRoute
  '/_app/policies/whitelists/': typeof AppPoliciesWhitelistsIndexRoute
  '/_app/settings/governance/': typeof AppSettingsGovernanceIndexRoute
  '/_app/settings/teams/': typeof AppSettingsTeamsIndexRoute
  '/_app/signers/$signerId/': typeof AppSignersSignerIdIndexRoute
  '/_app/vaults/$vaultId/': typeof AppVaultsVaultIdIndexRoute
  '/_app/policies/transactions/$policyId/versions': typeof AppPoliciesTransactionsPolicyIdVersionsRouteRouteWithChildren
  '/_app/policies/whitelists/$whitelistId/versions': typeof AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteWithChildren
  '/_app/vaults/$vaultId/addresses/$addressId': typeof AppVaultsVaultIdAddressesAddressIdRouteRouteWithChildren
  '/_app/policies/whitelists/$whitelistId/edit': typeof AppPoliciesWhitelistsWhitelistIdEditRoute
  '/_app/vaults/$vaultId/addresses/new': typeof AppVaultsVaultIdAddressesNewRoute
  '/_app/vaults/$vaultId/reshares/$reshareId': typeof AppVaultsVaultIdResharesReshareIdRoute
  '/_app/policies/transactions/$policyId/': typeof AppPoliciesTransactionsPolicyIdIndexRoute
  '/_app/policies/whitelists/$whitelistId/': typeof AppPoliciesWhitelistsWhitelistIdIndexRoute
  '/_app/vaults/$vaultId/addresses/': typeof AppVaultsVaultIdAddressesIndexRoute
  '/_app/policies/transactions/$policyId/versions/$versionNumber': typeof AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteWithChildren
  '/_app/policies/whitelists/$whitelistId/versions/$versionNumber': typeof AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteWithChildren
  '/_app/vaults/$vaultId/addresses/$addressId/': typeof AppVaultsVaultIdAddressesAddressIdIndexRoute
  '/_app/vaults/$vaultId/chain/$chain/addresses/$address': typeof AppVaultsVaultIdChainChainAddressesAddressRouteRouteWithChildren
  '/_app/policies/transactions/$policyId/versions/$versionNumber/': typeof AppPoliciesTransactionsPolicyIdVersionsVersionNumberIndexRoute
  '/_app/policies/whitelists/$whitelistId/versions/$versionNumber/': typeof AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberIndexRoute
  '/_app/vaults/$vaultId/chain/$chain/addresses/$address/transfer': typeof AppVaultsVaultIdChainChainAddressesAddressTransferRoute
  '/_app/vaults/$vaultId/chain/$chain/addresses/$address/': typeof AppVaultsVaultIdChainChainAddressesAddressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/logout'
    | '/account'
    | '/address-book'
    | '/compliance'
    | '/identities'
    | '/operations'
    | '/policies'
    | '/settings'
    | '/signers'
    | '/vaults'
    | '/overview'
    | '/forgot-password/'
    | '/login/'
    | '/sign-up/'
    | '/compliance/addresses'
    | '/compliance/transactions'
    | '/identities/$identityId'
    | '/operations/$operationId'
    | '/policies/transactions'
    | '/policies/whitelists'
    | '/settings/teams'
    | '/signers/$signerId'
    | '/vaults/$vaultId'
    | '/account/security'
    | '/compliance/alerts'
    | '/compliance/reports'
    | '/identities/new'
    | '/settings/audit'
    | '/settings/backups'
    | '/settings/billing'
    | '/settings/members'
    | '/settings/roles'
    | '/settings/workspaces'
    | '/signers/new'
    | '/vaults/layouts'
    | '/vaults/new'
    | '/vaults/tabs'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/account/'
    | '/address-book/'
    | '/compliance/'
    | '/identities/'
    | '/settings/'
    | '/signers/'
    | '/vaults/'
    | '/login/error'
    | '/login/verify'
    | '/policies/transactions/$policyId'
    | '/policies/whitelists/$whitelistId'
    | '/vaults/$vaultId/addresses'
    | '/compliance/addresses/$address'
    | '/compliance/transactions/$id'
    | '/identities/$identityId/edit'
    | '/policies/whitelists/new'
    | '/settings/governance/pending'
    | '/settings/teams/$teamId'
    | '/vaults/$vaultId/edit'
    | '/api/dev/email/$template'
    | '/api/openapi/app/schema'
    | '/compliance/addresses/'
    | '/compliance/transactions/'
    | '/identities/$identityId/'
    | '/policies/transactions/'
    | '/policies/whitelists/'
    | '/settings/governance'
    | '/settings/teams/'
    | '/signers/$signerId/'
    | '/vaults/$vaultId/'
    | '/policies/transactions/$policyId/versions'
    | '/policies/whitelists/$whitelistId/versions'
    | '/vaults/$vaultId/addresses/$addressId'
    | '/policies/whitelists/$whitelistId/edit'
    | '/vaults/$vaultId/addresses/new'
    | '/vaults/$vaultId/reshares/$reshareId'
    | '/policies/transactions/$policyId/'
    | '/policies/whitelists/$whitelistId/'
    | '/vaults/$vaultId/addresses/'
    | '/policies/transactions/$policyId/versions/$versionNumber'
    | '/policies/whitelists/$whitelistId/versions/$versionNumber'
    | '/vaults/$vaultId/addresses/$addressId/'
    | '/vaults/$vaultId/chain/$chain/addresses/$address'
    | '/policies/transactions/$policyId/versions/$versionNumber/'
    | '/policies/whitelists/$whitelistId/versions/$versionNumber/'
    | '/vaults/$vaultId/chain/$chain/addresses/$address/transfer'
    | '/vaults/$vaultId/chain/$chain/addresses/$address/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/operations'
    | '/policies'
    | '/overview'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/operations/$operationId'
    | '/account/security'
    | '/compliance/alerts'
    | '/compliance/reports'
    | '/identities/new'
    | '/settings/audit'
    | '/settings/backups'
    | '/settings/billing'
    | '/settings/members'
    | '/settings/roles'
    | '/settings/workspaces'
    | '/signers/new'
    | '/vaults/layouts'
    | '/vaults/new'
    | '/vaults/tabs'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/account'
    | '/address-book'
    | '/compliance'
    | '/identities'
    | '/settings'
    | '/signers'
    | '/vaults'
    | '/login/error'
    | '/login/verify'
    | '/compliance/addresses/$address'
    | '/compliance/transactions/$id'
    | '/identities/$identityId/edit'
    | '/policies/whitelists/new'
    | '/settings/governance/pending'
    | '/settings/teams/$teamId'
    | '/vaults/$vaultId/edit'
    | '/api/dev/email/$template'
    | '/api/openapi/app/schema'
    | '/compliance/addresses'
    | '/compliance/transactions'
    | '/identities/$identityId'
    | '/policies/transactions'
    | '/policies/whitelists'
    | '/settings/governance'
    | '/settings/teams'
    | '/signers/$signerId'
    | '/vaults/$vaultId'
    | '/policies/transactions/$policyId/versions'
    | '/policies/whitelists/$whitelistId/versions'
    | '/policies/whitelists/$whitelistId/edit'
    | '/vaults/$vaultId/addresses/new'
    | '/vaults/$vaultId/reshares/$reshareId'
    | '/policies/transactions/$policyId'
    | '/policies/whitelists/$whitelistId'
    | '/vaults/$vaultId/addresses'
    | '/vaults/$vaultId/addresses/$addressId'
    | '/policies/transactions/$policyId/versions/$versionNumber'
    | '/policies/whitelists/$whitelistId/versions/$versionNumber'
    | '/vaults/$vaultId/chain/$chain/addresses/$address/transfer'
    | '/vaults/$vaultId/chain/$chain/addresses/$address'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/_app'
    | '/logout'
    | '/_app/account'
    | '/_app/address-book'
    | '/_app/compliance'
    | '/_app/identities'
    | '/_app/operations'
    | '/_app/policies'
    | '/_app/settings'
    | '/_app/signers'
    | '/_app/vaults'
    | '/_app/overview'
    | '/forgot-password/'
    | '/login/'
    | '/sign-up/'
    | '/_app/compliance/addresses'
    | '/_app/compliance/transactions'
    | '/_app/identities/$identityId'
    | '/_app/operations/$operationId'
    | '/_app/policies/transactions'
    | '/_app/policies/whitelists'
    | '/_app/settings/teams'
    | '/_app/signers/$signerId'
    | '/_app/vaults/$vaultId'
    | '/_app/account/security'
    | '/_app/compliance/alerts'
    | '/_app/compliance/reports'
    | '/_app/identities/new'
    | '/_app/settings/audit'
    | '/_app/settings/backups'
    | '/_app/settings/billing'
    | '/_app/settings/members'
    | '/_app/settings/roles'
    | '/_app/settings/workspaces'
    | '/_app/signers/new'
    | '/_app/vaults/layouts'
    | '/_app/vaults/new'
    | '/_app/vaults/tabs'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/_app/account/'
    | '/_app/address-book/'
    | '/_app/compliance/'
    | '/_app/identities/'
    | '/_app/settings/'
    | '/_app/signers/'
    | '/_app/vaults/'
    | '/login/error/'
    | '/login/verify/'
    | '/_app/policies/transactions/$policyId'
    | '/_app/policies/whitelists/$whitelistId'
    | '/_app/vaults/$vaultId/addresses'
    | '/_app/compliance/addresses/$address'
    | '/_app/compliance/transactions/$id'
    | '/_app/identities/$identityId/edit'
    | '/_app/policies/whitelists/new'
    | '/_app/settings/governance/pending'
    | '/_app/settings/teams/$teamId'
    | '/_app/vaults/$vaultId/edit'
    | '/api/dev/email/$template'
    | '/api/openapi/app/schema'
    | '/_app/compliance/addresses/'
    | '/_app/compliance/transactions/'
    | '/_app/identities/$identityId/'
    | '/_app/policies/transactions/'
    | '/_app/policies/whitelists/'
    | '/_app/settings/governance/'
    | '/_app/settings/teams/'
    | '/_app/signers/$signerId/'
    | '/_app/vaults/$vaultId/'
    | '/_app/policies/transactions/$policyId/versions'
    | '/_app/policies/whitelists/$whitelistId/versions'
    | '/_app/vaults/$vaultId/addresses/$addressId'
    | '/_app/policies/whitelists/$whitelistId/edit'
    | '/_app/vaults/$vaultId/addresses/new'
    | '/_app/vaults/$vaultId/reshares/$reshareId'
    | '/_app/policies/transactions/$policyId/'
    | '/_app/policies/whitelists/$whitelistId/'
    | '/_app/vaults/$vaultId/addresses/'
    | '/_app/policies/transactions/$policyId/versions/$versionNumber'
    | '/_app/policies/whitelists/$whitelistId/versions/$versionNumber'
    | '/_app/vaults/$vaultId/addresses/$addressId/'
    | '/_app/vaults/$vaultId/chain/$chain/addresses/$address'
    | '/_app/policies/transactions/$policyId/versions/$versionNumber/'
    | '/_app/policies/whitelists/$whitelistId/versions/$versionNumber/'
    | '/_app/vaults/$vaultId/chain/$chain/addresses/$address/transfer'
    | '/_app/vaults/$vaultId/chain/$chain/addresses/$address/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRouteRoute: typeof ForgotPasswordRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  SignUpRouteRoute: typeof SignUpRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ApiOpenapiAppRoute: typeof ApiOpenapiAppRouteWithChildren
  ApiOpenapiAuthRoute: typeof ApiOpenapiAuthRoute
  ApiRestSplatRoute: typeof ApiRestSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiDevEmailTemplateRoute: typeof ApiDevEmailTemplateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof SignUpRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof ForgotPasswordRouteRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vaults': {
      id: '/_app/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof AppVaultsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signers': {
      id: '/_app/signers'
      path: '/signers'
      fullPath: '/signers'
      preLoaderRoute: typeof AppSignersRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies': {
      id: '/_app/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AppPoliciesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations': {
      id: '/_app/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AppOperationsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/identities': {
      id: '/_app/identities'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof AppIdentitiesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/address-book': {
      id: '/_app/address-book'
      path: '/address-book'
      fullPath: '/address-book'
      preLoaderRoute: typeof AppAddressBookRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/login/verify/': {
      id: '/login/verify/'
      path: '/verify'
      fullPath: '/login/verify'
      preLoaderRoute: typeof LoginVerifyIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/error/': {
      id: '/login/error/'
      path: '/error'
      fullPath: '/login/error'
      preLoaderRoute: typeof LoginErrorIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/_app/vaults/': {
      id: '/_app/vaults/'
      path: '/'
      fullPath: '/vaults/'
      preLoaderRoute: typeof AppVaultsIndexRouteImport
      parentRoute: typeof AppVaultsRouteRoute
    }
    '/_app/signers/': {
      id: '/_app/signers/'
      path: '/'
      fullPath: '/signers/'
      preLoaderRoute: typeof AppSignersIndexRouteImport
      parentRoute: typeof AppSignersRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/identities/': {
      id: '/_app/identities/'
      path: '/'
      fullPath: '/identities/'
      preLoaderRoute: typeof AppIdentitiesIndexRouteImport
      parentRoute: typeof AppIdentitiesRouteRoute
    }
    '/_app/compliance/': {
      id: '/_app/compliance/'
      path: '/'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AppComplianceIndexRouteImport
      parentRoute: typeof AppComplianceRouteRoute
    }
    '/_app/address-book/': {
      id: '/_app/address-book/'
      path: '/'
      fullPath: '/address-book/'
      preLoaderRoute: typeof AppAddressBookIndexRouteImport
      parentRoute: typeof AppAddressBookRouteRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rest/$': {
      id: '/api/rest/$'
      path: '/api/rest/$'
      fullPath: '/api/rest/$'
      preLoaderRoute: typeof ApiRestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/auth': {
      id: '/api/openapi/auth'
      path: '/api/openapi/auth'
      fullPath: '/api/openapi/auth'
      preLoaderRoute: typeof ApiOpenapiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/app': {
      id: '/api/openapi/app'
      path: '/api/openapi/app'
      fullPath: '/api/openapi/app'
      preLoaderRoute: typeof ApiOpenapiAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vaults/tabs': {
      id: '/_app/vaults/tabs'
      path: '/tabs'
      fullPath: '/vaults/tabs'
      preLoaderRoute: typeof AppVaultsTabsRouteImport
      parentRoute: typeof AppVaultsRouteRoute
    }
    '/_app/vaults/new': {
      id: '/_app/vaults/new'
      path: '/new'
      fullPath: '/vaults/new'
      preLoaderRoute: typeof AppVaultsNewRouteImport
      parentRoute: typeof AppVaultsRouteRoute
    }
    '/_app/vaults/layouts': {
      id: '/_app/vaults/layouts'
      path: '/layouts'
      fullPath: '/vaults/layouts'
      preLoaderRoute: typeof AppVaultsLayoutsRouteImport
      parentRoute: typeof AppVaultsRouteRoute
    }
    '/_app/signers/new': {
      id: '/_app/signers/new'
      path: '/new'
      fullPath: '/signers/new'
      preLoaderRoute: typeof AppSignersNewRouteImport
      parentRoute: typeof AppSignersRouteRoute
    }
    '/_app/settings/workspaces': {
      id: '/_app/settings/workspaces'
      path: '/workspaces'
      fullPath: '/settings/workspaces'
      preLoaderRoute: typeof AppSettingsWorkspacesRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/backups': {
      id: '/_app/settings/backups'
      path: '/backups'
      fullPath: '/settings/backups'
      preLoaderRoute: typeof AppSettingsBackupsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/identities/new': {
      id: '/_app/identities/new'
      path: '/new'
      fullPath: '/identities/new'
      preLoaderRoute: typeof AppIdentitiesNewRouteImport
      parentRoute: typeof AppIdentitiesRouteRoute
    }
    '/_app/compliance/reports': {
      id: '/_app/compliance/reports'
      path: '/reports'
      fullPath: '/compliance/reports'
      preLoaderRoute: typeof AppComplianceReportsRouteImport
      parentRoute: typeof AppComplianceRouteRoute
    }
    '/_app/compliance/alerts': {
      id: '/_app/compliance/alerts'
      path: '/alerts'
      fullPath: '/compliance/alerts'
      preLoaderRoute: typeof AppComplianceAlertsRouteImport
      parentRoute: typeof AppComplianceRouteRoute
    }
    '/_app/account/security': {
      id: '/_app/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AppAccountSecurityRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/_app/vaults/$vaultId': {
      id: '/_app/vaults/$vaultId'
      path: '/$vaultId'
      fullPath: '/vaults/$vaultId'
      preLoaderRoute: typeof AppVaultsVaultIdRouteRouteImport
      parentRoute: typeof AppVaultsRouteRoute
    }
    '/_app/signers/$signerId': {
      id: '/_app/signers/$signerId'
      path: '/$signerId'
      fullPath: '/signers/$signerId'
      preLoaderRoute: typeof AppSignersSignerIdRouteRouteImport
      parentRoute: typeof AppSignersRouteRoute
    }
    '/_app/settings/teams': {
      id: '/_app/settings/teams'
      path: '/teams'
      fullPath: '/settings/teams'
      preLoaderRoute: typeof AppSettingsTeamsRouteRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/policies/whitelists': {
      id: '/_app/policies/whitelists'
      path: '/whitelists'
      fullPath: '/policies/whitelists'
      preLoaderRoute: typeof AppPoliciesWhitelistsRouteRouteImport
      parentRoute: typeof AppPoliciesRouteRoute
    }
    '/_app/policies/transactions': {
      id: '/_app/policies/transactions'
      path: '/transactions'
      fullPath: '/policies/transactions'
      preLoaderRoute: typeof AppPoliciesTransactionsRouteRouteImport
      parentRoute: typeof AppPoliciesRouteRoute
    }
    '/_app/operations/$operationId': {
      id: '/_app/operations/$operationId'
      path: '/$operationId'
      fullPath: '/operations/$operationId'
      preLoaderRoute: typeof AppOperationsOperationIdRouteRouteImport
      parentRoute: typeof AppOperationsRouteRoute
    }
    '/_app/identities/$identityId': {
      id: '/_app/identities/$identityId'
      path: '/$identityId'
      fullPath: '/identities/$identityId'
      preLoaderRoute: typeof AppIdentitiesIdentityIdRouteRouteImport
      parentRoute: typeof AppIdentitiesRouteRoute
    }
    '/_app/compliance/transactions': {
      id: '/_app/compliance/transactions'
      path: '/transactions'
      fullPath: '/compliance/transactions'
      preLoaderRoute: typeof AppComplianceTransactionsRouteRouteImport
      parentRoute: typeof AppComplianceRouteRoute
    }
    '/_app/compliance/addresses': {
      id: '/_app/compliance/addresses'
      path: '/addresses'
      fullPath: '/compliance/addresses'
      preLoaderRoute: typeof AppComplianceAddressesRouteRouteImport
      parentRoute: typeof AppComplianceRouteRoute
    }
    '/_app/vaults/$vaultId/': {
      id: '/_app/vaults/$vaultId/'
      path: '/'
      fullPath: '/vaults/$vaultId/'
      preLoaderRoute: typeof AppVaultsVaultIdIndexRouteImport
      parentRoute: typeof AppVaultsVaultIdRouteRoute
    }
    '/_app/signers/$signerId/': {
      id: '/_app/signers/$signerId/'
      path: '/'
      fullPath: '/signers/$signerId/'
      preLoaderRoute: typeof AppSignersSignerIdIndexRouteImport
      parentRoute: typeof AppSignersSignerIdRouteRoute
    }
    '/_app/settings/teams/': {
      id: '/_app/settings/teams/'
      path: '/'
      fullPath: '/settings/teams/'
      preLoaderRoute: typeof AppSettingsTeamsIndexRouteImport
      parentRoute: typeof AppSettingsTeamsRouteRoute
    }
    '/_app/settings/governance/': {
      id: '/_app/settings/governance/'
      path: '/governance'
      fullPath: '/settings/governance'
      preLoaderRoute: typeof AppSettingsGovernanceIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/policies/whitelists/': {
      id: '/_app/policies/whitelists/'
      path: '/'
      fullPath: '/policies/whitelists/'
      preLoaderRoute: typeof AppPoliciesWhitelistsIndexRouteImport
      parentRoute: typeof AppPoliciesWhitelistsRouteRoute
    }
    '/_app/policies/transactions/': {
      id: '/_app/policies/transactions/'
      path: '/'
      fullPath: '/policies/transactions/'
      preLoaderRoute: typeof AppPoliciesTransactionsIndexRouteImport
      parentRoute: typeof AppPoliciesTransactionsRouteRoute
    }
    '/_app/identities/$identityId/': {
      id: '/_app/identities/$identityId/'
      path: '/'
      fullPath: '/identities/$identityId/'
      preLoaderRoute: typeof AppIdentitiesIdentityIdIndexRouteImport
      parentRoute: typeof AppIdentitiesIdentityIdRouteRoute
    }
    '/_app/compliance/transactions/': {
      id: '/_app/compliance/transactions/'
      path: '/'
      fullPath: '/compliance/transactions/'
      preLoaderRoute: typeof AppComplianceTransactionsIndexRouteImport
      parentRoute: typeof AppComplianceTransactionsRouteRoute
    }
    '/_app/compliance/addresses/': {
      id: '/_app/compliance/addresses/'
      path: '/'
      fullPath: '/compliance/addresses/'
      preLoaderRoute: typeof AppComplianceAddressesIndexRouteImport
      parentRoute: typeof AppComplianceAddressesRouteRoute
    }
    '/api/openapi/app/schema': {
      id: '/api/openapi/app/schema'
      path: '/schema'
      fullPath: '/api/openapi/app/schema'
      preLoaderRoute: typeof ApiOpenapiAppSchemaRouteImport
      parentRoute: typeof ApiOpenapiAppRoute
    }
    '/api/dev/email/$template': {
      id: '/api/dev/email/$template'
      path: '/api/dev/email/$template'
      fullPath: '/api/dev/email/$template'
      preLoaderRoute: typeof ApiDevEmailTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vaults/$vaultId/edit': {
      id: '/_app/vaults/$vaultId/edit'
      path: '/edit'
      fullPath: '/vaults/$vaultId/edit'
      preLoaderRoute: typeof AppVaultsVaultIdEditRouteImport
      parentRoute: typeof AppVaultsVaultIdRouteRoute
    }
    '/_app/settings/teams/$teamId': {
      id: '/_app/settings/teams/$teamId'
      path: '/$teamId'
      fullPath: '/settings/teams/$teamId'
      preLoaderRoute: typeof AppSettingsTeamsTeamIdRouteImport
      parentRoute: typeof AppSettingsTeamsRouteRoute
    }
    '/_app/settings/governance/pending': {
      id: '/_app/settings/governance/pending'
      path: '/governance/pending'
      fullPath: '/settings/governance/pending'
      preLoaderRoute: typeof AppSettingsGovernancePendingRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/policies/whitelists/new': {
      id: '/_app/policies/whitelists/new'
      path: '/new'
      fullPath: '/policies/whitelists/new'
      preLoaderRoute: typeof AppPoliciesWhitelistsNewRouteImport
      parentRoute: typeof AppPoliciesWhitelistsRouteRoute
    }
    '/_app/identities/$identityId/edit': {
      id: '/_app/identities/$identityId/edit'
      path: '/edit'
      fullPath: '/identities/$identityId/edit'
      preLoaderRoute: typeof AppIdentitiesIdentityIdEditRouteImport
      parentRoute: typeof AppIdentitiesIdentityIdRouteRoute
    }
    '/_app/compliance/transactions/$id': {
      id: '/_app/compliance/transactions/$id'
      path: '/$id'
      fullPath: '/compliance/transactions/$id'
      preLoaderRoute: typeof AppComplianceTransactionsIdRouteImport
      parentRoute: typeof AppComplianceTransactionsRouteRoute
    }
    '/_app/compliance/addresses/$address': {
      id: '/_app/compliance/addresses/$address'
      path: '/$address'
      fullPath: '/compliance/addresses/$address'
      preLoaderRoute: typeof AppComplianceAddressesAddressRouteImport
      parentRoute: typeof AppComplianceAddressesRouteRoute
    }
    '/_app/vaults/$vaultId/addresses': {
      id: '/_app/vaults/$vaultId/addresses'
      path: '/addresses'
      fullPath: '/vaults/$vaultId/addresses'
      preLoaderRoute: typeof AppVaultsVaultIdAddressesRouteRouteImport
      parentRoute: typeof AppVaultsVaultIdRouteRoute
    }
    '/_app/policies/whitelists/$whitelistId': {
      id: '/_app/policies/whitelists/$whitelistId'
      path: '/$whitelistId'
      fullPath: '/policies/whitelists/$whitelistId'
      preLoaderRoute: typeof AppPoliciesWhitelistsWhitelistIdRouteRouteImport
      parentRoute: typeof AppPoliciesWhitelistsRouteRoute
    }
    '/_app/policies/transactions/$policyId': {
      id: '/_app/policies/transactions/$policyId'
      path: '/$policyId'
      fullPath: '/policies/transactions/$policyId'
      preLoaderRoute: typeof AppPoliciesTransactionsPolicyIdRouteRouteImport
      parentRoute: typeof AppPoliciesTransactionsRouteRoute
    }
    '/_app/vaults/$vaultId/addresses/': {
      id: '/_app/vaults/$vaultId/addresses/'
      path: '/'
      fullPath: '/vaults/$vaultId/addresses/'
      preLoaderRoute: typeof AppVaultsVaultIdAddressesIndexRouteImport
      parentRoute: typeof AppVaultsVaultIdAddressesRouteRoute
    }
    '/_app/policies/whitelists/$whitelistId/': {
      id: '/_app/policies/whitelists/$whitelistId/'
      path: '/'
      fullPath: '/policies/whitelists/$whitelistId/'
      preLoaderRoute: typeof AppPoliciesWhitelistsWhitelistIdIndexRouteImport
      parentRoute: typeof AppPoliciesWhitelistsWhitelistIdRouteRoute
    }
    '/_app/policies/transactions/$policyId/': {
      id: '/_app/policies/transactions/$policyId/'
      path: '/'
      fullPath: '/policies/transactions/$policyId/'
      preLoaderRoute: typeof AppPoliciesTransactionsPolicyIdIndexRouteImport
      parentRoute: typeof AppPoliciesTransactionsPolicyIdRouteRoute
    }
    '/_app/vaults/$vaultId/reshares/$reshareId': {
      id: '/_app/vaults/$vaultId/reshares/$reshareId'
      path: '/reshares/$reshareId'
      fullPath: '/vaults/$vaultId/reshares/$reshareId'
      preLoaderRoute: typeof AppVaultsVaultIdResharesReshareIdRouteImport
      parentRoute: typeof AppVaultsVaultIdRouteRoute
    }
    '/_app/vaults/$vaultId/addresses/new': {
      id: '/_app/vaults/$vaultId/addresses/new'
      path: '/new'
      fullPath: '/vaults/$vaultId/addresses/new'
      preLoaderRoute: typeof AppVaultsVaultIdAddressesNewRouteImport
      parentRoute: typeof AppVaultsVaultIdAddressesRouteRoute
    }
    '/_app/policies/whitelists/$whitelistId/edit': {
      id: '/_app/policies/whitelists/$whitelistId/edit'
      path: '/edit'
      fullPath: '/policies/whitelists/$whitelistId/edit'
      preLoaderRoute: typeof AppPoliciesWhitelistsWhitelistIdEditRouteImport
      parentRoute: typeof AppPoliciesWhitelistsWhitelistIdRouteRoute
    }
    '/_app/vaults/$vaultId/addresses/$addressId': {
      id: '/_app/vaults/$vaultId/addresses/$addressId'
      path: '/$addressId'
      fullPath: '/vaults/$vaultId/addresses/$addressId'
      preLoaderRoute: typeof AppVaultsVaultIdAddressesAddressIdRouteRouteImport
      parentRoute: typeof AppVaultsVaultIdAddressesRouteRoute
    }
    '/_app/policies/whitelists/$whitelistId/versions': {
      id: '/_app/policies/whitelists/$whitelistId/versions'
      path: '/versions'
      fullPath: '/policies/whitelists/$whitelistId/versions'
      preLoaderRoute: typeof AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteImport
      parentRoute: typeof AppPoliciesWhitelistsWhitelistIdRouteRoute
    }
    '/_app/policies/transactions/$policyId/versions': {
      id: '/_app/policies/transactions/$policyId/versions'
      path: '/versions'
      fullPath: '/policies/transactions/$policyId/versions'
      preLoaderRoute: typeof AppPoliciesTransactionsPolicyIdVersionsRouteRouteImport
      parentRoute: typeof AppPoliciesTransactionsPolicyIdRouteRoute
    }
    '/_app/vaults/$vaultId/addresses/$addressId/': {
      id: '/_app/vaults/$vaultId/addresses/$addressId/'
      path: '/'
      fullPath: '/vaults/$vaultId/addresses/$addressId/'
      preLoaderRoute: typeof AppVaultsVaultIdAddressesAddressIdIndexRouteImport
      parentRoute: typeof AppVaultsVaultIdAddressesAddressIdRouteRoute
    }
    '/_app/policies/whitelists/$whitelistId/versions/$versionNumber': {
      id: '/_app/policies/whitelists/$whitelistId/versions/$versionNumber'
      path: '/$versionNumber'
      fullPath: '/policies/whitelists/$whitelistId/versions/$versionNumber'
      preLoaderRoute: typeof AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteImport
      parentRoute: typeof AppPoliciesWhitelistsWhitelistIdVersionsRouteRoute
    }
    '/_app/policies/transactions/$policyId/versions/$versionNumber': {
      id: '/_app/policies/transactions/$policyId/versions/$versionNumber'
      path: '/$versionNumber'
      fullPath: '/policies/transactions/$policyId/versions/$versionNumber'
      preLoaderRoute: typeof AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteImport
      parentRoute: typeof AppPoliciesTransactionsPolicyIdVersionsRouteRoute
    }
    '/_app/policies/whitelists/$whitelistId/versions/$versionNumber/': {
      id: '/_app/policies/whitelists/$whitelistId/versions/$versionNumber/'
      path: '/'
      fullPath: '/policies/whitelists/$whitelistId/versions/$versionNumber/'
      preLoaderRoute: typeof AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberIndexRouteImport
      parentRoute: typeof AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRoute
    }
    '/_app/policies/transactions/$policyId/versions/$versionNumber/': {
      id: '/_app/policies/transactions/$policyId/versions/$versionNumber/'
      path: '/'
      fullPath: '/policies/transactions/$policyId/versions/$versionNumber/'
      preLoaderRoute: typeof AppPoliciesTransactionsPolicyIdVersionsVersionNumberIndexRouteImport
      parentRoute: typeof AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRoute
    }
    '/_app/vaults/$vaultId/chain/$chain/addresses/$address': {
      id: '/_app/vaults/$vaultId/chain/$chain/addresses/$address'
      path: '/chain/$chain/addresses/$address'
      fullPath: '/vaults/$vaultId/chain/$chain/addresses/$address'
      preLoaderRoute: typeof AppVaultsVaultIdChainChainAddressesAddressRouteRouteImport
      parentRoute: typeof AppVaultsVaultIdRouteRoute
    }
    '/_app/vaults/$vaultId/chain/$chain/addresses/$address/': {
      id: '/_app/vaults/$vaultId/chain/$chain/addresses/$address/'
      path: '/'
      fullPath: '/vaults/$vaultId/chain/$chain/addresses/$address/'
      preLoaderRoute: typeof AppVaultsVaultIdChainChainAddressesAddressIndexRouteImport
      parentRoute: typeof AppVaultsVaultIdChainChainAddressesAddressRouteRoute
    }
    '/_app/vaults/$vaultId/chain/$chain/addresses/$address/transfer': {
      id: '/_app/vaults/$vaultId/chain/$chain/addresses/$address/transfer'
      path: '/transfer'
      fullPath: '/vaults/$vaultId/chain/$chain/addresses/$address/transfer'
      preLoaderRoute: typeof AppVaultsVaultIdChainChainAddressesAddressTransferRouteImport
      parentRoute: typeof AppVaultsVaultIdChainChainAddressesAddressRouteRoute
    }
  }
}

interface ForgotPasswordRouteRouteChildren {
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
}

const ForgotPasswordRouteRouteChildren: ForgotPasswordRouteRouteChildren = {
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
}

const ForgotPasswordRouteRouteWithChildren =
  ForgotPasswordRouteRoute._addFileChildren(ForgotPasswordRouteRouteChildren)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
  LoginErrorIndexRoute: typeof LoginErrorIndexRoute
  LoginVerifyIndexRoute: typeof LoginVerifyIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
  LoginErrorIndexRoute: LoginErrorIndexRoute,
  LoginVerifyIndexRoute: LoginVerifyIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface SignUpRouteRouteChildren {
  SignUpIndexRoute: typeof SignUpIndexRoute
}

const SignUpRouteRouteChildren: SignUpRouteRouteChildren = {
  SignUpIndexRoute: SignUpIndexRoute,
}

const SignUpRouteRouteWithChildren = SignUpRouteRoute._addFileChildren(
  SignUpRouteRouteChildren,
)

interface AppAccountRouteRouteChildren {
  AppAccountSecurityRoute: typeof AppAccountSecurityRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteRouteChildren: AppAccountRouteRouteChildren = {
  AppAccountSecurityRoute: AppAccountSecurityRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteRouteWithChildren = AppAccountRouteRoute._addFileChildren(
  AppAccountRouteRouteChildren,
)

interface AppAddressBookRouteRouteChildren {
  AppAddressBookIndexRoute: typeof AppAddressBookIndexRoute
}

const AppAddressBookRouteRouteChildren: AppAddressBookRouteRouteChildren = {
  AppAddressBookIndexRoute: AppAddressBookIndexRoute,
}

const AppAddressBookRouteRouteWithChildren =
  AppAddressBookRouteRoute._addFileChildren(AppAddressBookRouteRouteChildren)

interface AppComplianceAddressesRouteRouteChildren {
  AppComplianceAddressesAddressRoute: typeof AppComplianceAddressesAddressRoute
  AppComplianceAddressesIndexRoute: typeof AppComplianceAddressesIndexRoute
}

const AppComplianceAddressesRouteRouteChildren: AppComplianceAddressesRouteRouteChildren =
  {
    AppComplianceAddressesAddressRoute: AppComplianceAddressesAddressRoute,
    AppComplianceAddressesIndexRoute: AppComplianceAddressesIndexRoute,
  }

const AppComplianceAddressesRouteRouteWithChildren =
  AppComplianceAddressesRouteRoute._addFileChildren(
    AppComplianceAddressesRouteRouteChildren,
  )

interface AppComplianceTransactionsRouteRouteChildren {
  AppComplianceTransactionsIdRoute: typeof AppComplianceTransactionsIdRoute
  AppComplianceTransactionsIndexRoute: typeof AppComplianceTransactionsIndexRoute
}

const AppComplianceTransactionsRouteRouteChildren: AppComplianceTransactionsRouteRouteChildren =
  {
    AppComplianceTransactionsIdRoute: AppComplianceTransactionsIdRoute,
    AppComplianceTransactionsIndexRoute: AppComplianceTransactionsIndexRoute,
  }

const AppComplianceTransactionsRouteRouteWithChildren =
  AppComplianceTransactionsRouteRoute._addFileChildren(
    AppComplianceTransactionsRouteRouteChildren,
  )

interface AppComplianceRouteRouteChildren {
  AppComplianceAddressesRouteRoute: typeof AppComplianceAddressesRouteRouteWithChildren
  AppComplianceTransactionsRouteRoute: typeof AppComplianceTransactionsRouteRouteWithChildren
  AppComplianceAlertsRoute: typeof AppComplianceAlertsRoute
  AppComplianceReportsRoute: typeof AppComplianceReportsRoute
  AppComplianceIndexRoute: typeof AppComplianceIndexRoute
}

const AppComplianceRouteRouteChildren: AppComplianceRouteRouteChildren = {
  AppComplianceAddressesRouteRoute:
    AppComplianceAddressesRouteRouteWithChildren,
  AppComplianceTransactionsRouteRoute:
    AppComplianceTransactionsRouteRouteWithChildren,
  AppComplianceAlertsRoute: AppComplianceAlertsRoute,
  AppComplianceReportsRoute: AppComplianceReportsRoute,
  AppComplianceIndexRoute: AppComplianceIndexRoute,
}

const AppComplianceRouteRouteWithChildren =
  AppComplianceRouteRoute._addFileChildren(AppComplianceRouteRouteChildren)

interface AppIdentitiesIdentityIdRouteRouteChildren {
  AppIdentitiesIdentityIdEditRoute: typeof AppIdentitiesIdentityIdEditRoute
  AppIdentitiesIdentityIdIndexRoute: typeof AppIdentitiesIdentityIdIndexRoute
}

const AppIdentitiesIdentityIdRouteRouteChildren: AppIdentitiesIdentityIdRouteRouteChildren =
  {
    AppIdentitiesIdentityIdEditRoute: AppIdentitiesIdentityIdEditRoute,
    AppIdentitiesIdentityIdIndexRoute: AppIdentitiesIdentityIdIndexRoute,
  }

const AppIdentitiesIdentityIdRouteRouteWithChildren =
  AppIdentitiesIdentityIdRouteRoute._addFileChildren(
    AppIdentitiesIdentityIdRouteRouteChildren,
  )

interface AppIdentitiesRouteRouteChildren {
  AppIdentitiesIdentityIdRouteRoute: typeof AppIdentitiesIdentityIdRouteRouteWithChildren
  AppIdentitiesNewRoute: typeof AppIdentitiesNewRoute
  AppIdentitiesIndexRoute: typeof AppIdentitiesIndexRoute
}

const AppIdentitiesRouteRouteChildren: AppIdentitiesRouteRouteChildren = {
  AppIdentitiesIdentityIdRouteRoute:
    AppIdentitiesIdentityIdRouteRouteWithChildren,
  AppIdentitiesNewRoute: AppIdentitiesNewRoute,
  AppIdentitiesIndexRoute: AppIdentitiesIndexRoute,
}

const AppIdentitiesRouteRouteWithChildren =
  AppIdentitiesRouteRoute._addFileChildren(AppIdentitiesRouteRouteChildren)

interface AppOperationsRouteRouteChildren {
  AppOperationsOperationIdRouteRoute: typeof AppOperationsOperationIdRouteRoute
}

const AppOperationsRouteRouteChildren: AppOperationsRouteRouteChildren = {
  AppOperationsOperationIdRouteRoute: AppOperationsOperationIdRouteRoute,
}

const AppOperationsRouteRouteWithChildren =
  AppOperationsRouteRoute._addFileChildren(AppOperationsRouteRouteChildren)

interface AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteChildren {
  AppPoliciesTransactionsPolicyIdVersionsVersionNumberIndexRoute: typeof AppPoliciesTransactionsPolicyIdVersionsVersionNumberIndexRoute
}

const AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteChildren: AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteChildren =
  {
    AppPoliciesTransactionsPolicyIdVersionsVersionNumberIndexRoute:
      AppPoliciesTransactionsPolicyIdVersionsVersionNumberIndexRoute,
  }

const AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteWithChildren =
  AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRoute._addFileChildren(
    AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteChildren,
  )

interface AppPoliciesTransactionsPolicyIdVersionsRouteRouteChildren {
  AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRoute: typeof AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteWithChildren
}

const AppPoliciesTransactionsPolicyIdVersionsRouteRouteChildren: AppPoliciesTransactionsPolicyIdVersionsRouteRouteChildren =
  {
    AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRoute:
      AppPoliciesTransactionsPolicyIdVersionsVersionNumberRouteRouteWithChildren,
  }

const AppPoliciesTransactionsPolicyIdVersionsRouteRouteWithChildren =
  AppPoliciesTransactionsPolicyIdVersionsRouteRoute._addFileChildren(
    AppPoliciesTransactionsPolicyIdVersionsRouteRouteChildren,
  )

interface AppPoliciesTransactionsPolicyIdRouteRouteChildren {
  AppPoliciesTransactionsPolicyIdVersionsRouteRoute: typeof AppPoliciesTransactionsPolicyIdVersionsRouteRouteWithChildren
  AppPoliciesTransactionsPolicyIdIndexRoute: typeof AppPoliciesTransactionsPolicyIdIndexRoute
}

const AppPoliciesTransactionsPolicyIdRouteRouteChildren: AppPoliciesTransactionsPolicyIdRouteRouteChildren =
  {
    AppPoliciesTransactionsPolicyIdVersionsRouteRoute:
      AppPoliciesTransactionsPolicyIdVersionsRouteRouteWithChildren,
    AppPoliciesTransactionsPolicyIdIndexRoute:
      AppPoliciesTransactionsPolicyIdIndexRoute,
  }

const AppPoliciesTransactionsPolicyIdRouteRouteWithChildren =
  AppPoliciesTransactionsPolicyIdRouteRoute._addFileChildren(
    AppPoliciesTransactionsPolicyIdRouteRouteChildren,
  )

interface AppPoliciesTransactionsRouteRouteChildren {
  AppPoliciesTransactionsPolicyIdRouteRoute: typeof AppPoliciesTransactionsPolicyIdRouteRouteWithChildren
  AppPoliciesTransactionsIndexRoute: typeof AppPoliciesTransactionsIndexRoute
}

const AppPoliciesTransactionsRouteRouteChildren: AppPoliciesTransactionsRouteRouteChildren =
  {
    AppPoliciesTransactionsPolicyIdRouteRoute:
      AppPoliciesTransactionsPolicyIdRouteRouteWithChildren,
    AppPoliciesTransactionsIndexRoute: AppPoliciesTransactionsIndexRoute,
  }

const AppPoliciesTransactionsRouteRouteWithChildren =
  AppPoliciesTransactionsRouteRoute._addFileChildren(
    AppPoliciesTransactionsRouteRouteChildren,
  )

interface AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteChildren {
  AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberIndexRoute: typeof AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberIndexRoute
}

const AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteChildren: AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteChildren =
  {
    AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberIndexRoute:
      AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberIndexRoute,
  }

const AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteWithChildren =
  AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRoute._addFileChildren(
    AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteChildren,
  )

interface AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteChildren {
  AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRoute: typeof AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteWithChildren
}

const AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteChildren: AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteChildren =
  {
    AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRoute:
      AppPoliciesWhitelistsWhitelistIdVersionsVersionNumberRouteRouteWithChildren,
  }

const AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteWithChildren =
  AppPoliciesWhitelistsWhitelistIdVersionsRouteRoute._addFileChildren(
    AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteChildren,
  )

interface AppPoliciesWhitelistsWhitelistIdRouteRouteChildren {
  AppPoliciesWhitelistsWhitelistIdVersionsRouteRoute: typeof AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteWithChildren
  AppPoliciesWhitelistsWhitelistIdEditRoute: typeof AppPoliciesWhitelistsWhitelistIdEditRoute
  AppPoliciesWhitelistsWhitelistIdIndexRoute: typeof AppPoliciesWhitelistsWhitelistIdIndexRoute
}

const AppPoliciesWhitelistsWhitelistIdRouteRouteChildren: AppPoliciesWhitelistsWhitelistIdRouteRouteChildren =
  {
    AppPoliciesWhitelistsWhitelistIdVersionsRouteRoute:
      AppPoliciesWhitelistsWhitelistIdVersionsRouteRouteWithChildren,
    AppPoliciesWhitelistsWhitelistIdEditRoute:
      AppPoliciesWhitelistsWhitelistIdEditRoute,
    AppPoliciesWhitelistsWhitelistIdIndexRoute:
      AppPoliciesWhitelistsWhitelistIdIndexRoute,
  }

const AppPoliciesWhitelistsWhitelistIdRouteRouteWithChildren =
  AppPoliciesWhitelistsWhitelistIdRouteRoute._addFileChildren(
    AppPoliciesWhitelistsWhitelistIdRouteRouteChildren,
  )

interface AppPoliciesWhitelistsRouteRouteChildren {
  AppPoliciesWhitelistsWhitelistIdRouteRoute: typeof AppPoliciesWhitelistsWhitelistIdRouteRouteWithChildren
  AppPoliciesWhitelistsNewRoute: typeof AppPoliciesWhitelistsNewRoute
  AppPoliciesWhitelistsIndexRoute: typeof AppPoliciesWhitelistsIndexRoute
}

const AppPoliciesWhitelistsRouteRouteChildren: AppPoliciesWhitelistsRouteRouteChildren =
  {
    AppPoliciesWhitelistsWhitelistIdRouteRoute:
      AppPoliciesWhitelistsWhitelistIdRouteRouteWithChildren,
    AppPoliciesWhitelistsNewRoute: AppPoliciesWhitelistsNewRoute,
    AppPoliciesWhitelistsIndexRoute: AppPoliciesWhitelistsIndexRoute,
  }

const AppPoliciesWhitelistsRouteRouteWithChildren =
  AppPoliciesWhitelistsRouteRoute._addFileChildren(
    AppPoliciesWhitelistsRouteRouteChildren,
  )

interface AppPoliciesRouteRouteChildren {
  AppPoliciesTransactionsRouteRoute: typeof AppPoliciesTransactionsRouteRouteWithChildren
  AppPoliciesWhitelistsRouteRoute: typeof AppPoliciesWhitelistsRouteRouteWithChildren
}

const AppPoliciesRouteRouteChildren: AppPoliciesRouteRouteChildren = {
  AppPoliciesTransactionsRouteRoute:
    AppPoliciesTransactionsRouteRouteWithChildren,
  AppPoliciesWhitelistsRouteRoute: AppPoliciesWhitelistsRouteRouteWithChildren,
}

const AppPoliciesRouteRouteWithChildren =
  AppPoliciesRouteRoute._addFileChildren(AppPoliciesRouteRouteChildren)

interface AppSettingsTeamsRouteRouteChildren {
  AppSettingsTeamsTeamIdRoute: typeof AppSettingsTeamsTeamIdRoute
  AppSettingsTeamsIndexRoute: typeof AppSettingsTeamsIndexRoute
}

const AppSettingsTeamsRouteRouteChildren: AppSettingsTeamsRouteRouteChildren = {
  AppSettingsTeamsTeamIdRoute: AppSettingsTeamsTeamIdRoute,
  AppSettingsTeamsIndexRoute: AppSettingsTeamsIndexRoute,
}

const AppSettingsTeamsRouteRouteWithChildren =
  AppSettingsTeamsRouteRoute._addFileChildren(
    AppSettingsTeamsRouteRouteChildren,
  )

interface AppSettingsRouteRouteChildren {
  AppSettingsTeamsRouteRoute: typeof AppSettingsTeamsRouteRouteWithChildren
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsBackupsRoute: typeof AppSettingsBackupsRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsWorkspacesRoute: typeof AppSettingsWorkspacesRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsGovernancePendingRoute: typeof AppSettingsGovernancePendingRoute
  AppSettingsGovernanceIndexRoute: typeof AppSettingsGovernanceIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsTeamsRouteRoute: AppSettingsTeamsRouteRouteWithChildren,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsBackupsRoute: AppSettingsBackupsRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsWorkspacesRoute: AppSettingsWorkspacesRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsGovernancePendingRoute: AppSettingsGovernancePendingRoute,
  AppSettingsGovernanceIndexRoute: AppSettingsGovernanceIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppSignersSignerIdRouteRouteChildren {
  AppSignersSignerIdIndexRoute: typeof AppSignersSignerIdIndexRoute
}

const AppSignersSignerIdRouteRouteChildren: AppSignersSignerIdRouteRouteChildren =
  {
    AppSignersSignerIdIndexRoute: AppSignersSignerIdIndexRoute,
  }

const AppSignersSignerIdRouteRouteWithChildren =
  AppSignersSignerIdRouteRoute._addFileChildren(
    AppSignersSignerIdRouteRouteChildren,
  )

interface AppSignersRouteRouteChildren {
  AppSignersSignerIdRouteRoute: typeof AppSignersSignerIdRouteRouteWithChildren
  AppSignersNewRoute: typeof AppSignersNewRoute
  AppSignersIndexRoute: typeof AppSignersIndexRoute
}

const AppSignersRouteRouteChildren: AppSignersRouteRouteChildren = {
  AppSignersSignerIdRouteRoute: AppSignersSignerIdRouteRouteWithChildren,
  AppSignersNewRoute: AppSignersNewRoute,
  AppSignersIndexRoute: AppSignersIndexRoute,
}

const AppSignersRouteRouteWithChildren = AppSignersRouteRoute._addFileChildren(
  AppSignersRouteRouteChildren,
)

interface AppVaultsVaultIdAddressesAddressIdRouteRouteChildren {
  AppVaultsVaultIdAddressesAddressIdIndexRoute: typeof AppVaultsVaultIdAddressesAddressIdIndexRoute
}

const AppVaultsVaultIdAddressesAddressIdRouteRouteChildren: AppVaultsVaultIdAddressesAddressIdRouteRouteChildren =
  {
    AppVaultsVaultIdAddressesAddressIdIndexRoute:
      AppVaultsVaultIdAddressesAddressIdIndexRoute,
  }

const AppVaultsVaultIdAddressesAddressIdRouteRouteWithChildren =
  AppVaultsVaultIdAddressesAddressIdRouteRoute._addFileChildren(
    AppVaultsVaultIdAddressesAddressIdRouteRouteChildren,
  )

interface AppVaultsVaultIdAddressesRouteRouteChildren {
  AppVaultsVaultIdAddressesAddressIdRouteRoute: typeof AppVaultsVaultIdAddressesAddressIdRouteRouteWithChildren
  AppVaultsVaultIdAddressesNewRoute: typeof AppVaultsVaultIdAddressesNewRoute
  AppVaultsVaultIdAddressesIndexRoute: typeof AppVaultsVaultIdAddressesIndexRoute
}

const AppVaultsVaultIdAddressesRouteRouteChildren: AppVaultsVaultIdAddressesRouteRouteChildren =
  {
    AppVaultsVaultIdAddressesAddressIdRouteRoute:
      AppVaultsVaultIdAddressesAddressIdRouteRouteWithChildren,
    AppVaultsVaultIdAddressesNewRoute: AppVaultsVaultIdAddressesNewRoute,
    AppVaultsVaultIdAddressesIndexRoute: AppVaultsVaultIdAddressesIndexRoute,
  }

const AppVaultsVaultIdAddressesRouteRouteWithChildren =
  AppVaultsVaultIdAddressesRouteRoute._addFileChildren(
    AppVaultsVaultIdAddressesRouteRouteChildren,
  )

interface AppVaultsVaultIdChainChainAddressesAddressRouteRouteChildren {
  AppVaultsVaultIdChainChainAddressesAddressTransferRoute: typeof AppVaultsVaultIdChainChainAddressesAddressTransferRoute
  AppVaultsVaultIdChainChainAddressesAddressIndexRoute: typeof AppVaultsVaultIdChainChainAddressesAddressIndexRoute
}

const AppVaultsVaultIdChainChainAddressesAddressRouteRouteChildren: AppVaultsVaultIdChainChainAddressesAddressRouteRouteChildren =
  {
    AppVaultsVaultIdChainChainAddressesAddressTransferRoute:
      AppVaultsVaultIdChainChainAddressesAddressTransferRoute,
    AppVaultsVaultIdChainChainAddressesAddressIndexRoute:
      AppVaultsVaultIdChainChainAddressesAddressIndexRoute,
  }

const AppVaultsVaultIdChainChainAddressesAddressRouteRouteWithChildren =
  AppVaultsVaultIdChainChainAddressesAddressRouteRoute._addFileChildren(
    AppVaultsVaultIdChainChainAddressesAddressRouteRouteChildren,
  )

interface AppVaultsVaultIdRouteRouteChildren {
  AppVaultsVaultIdAddressesRouteRoute: typeof AppVaultsVaultIdAddressesRouteRouteWithChildren
  AppVaultsVaultIdEditRoute: typeof AppVaultsVaultIdEditRoute
  AppVaultsVaultIdIndexRoute: typeof AppVaultsVaultIdIndexRoute
  AppVaultsVaultIdResharesReshareIdRoute: typeof AppVaultsVaultIdResharesReshareIdRoute
  AppVaultsVaultIdChainChainAddressesAddressRouteRoute: typeof AppVaultsVaultIdChainChainAddressesAddressRouteRouteWithChildren
}

const AppVaultsVaultIdRouteRouteChildren: AppVaultsVaultIdRouteRouteChildren = {
  AppVaultsVaultIdAddressesRouteRoute:
    AppVaultsVaultIdAddressesRouteRouteWithChildren,
  AppVaultsVaultIdEditRoute: AppVaultsVaultIdEditRoute,
  AppVaultsVaultIdIndexRoute: AppVaultsVaultIdIndexRoute,
  AppVaultsVaultIdResharesReshareIdRoute:
    AppVaultsVaultIdResharesReshareIdRoute,
  AppVaultsVaultIdChainChainAddressesAddressRouteRoute:
    AppVaultsVaultIdChainChainAddressesAddressRouteRouteWithChildren,
}

const AppVaultsVaultIdRouteRouteWithChildren =
  AppVaultsVaultIdRouteRoute._addFileChildren(
    AppVaultsVaultIdRouteRouteChildren,
  )

interface AppVaultsRouteRouteChildren {
  AppVaultsVaultIdRouteRoute: typeof AppVaultsVaultIdRouteRouteWithChildren
  AppVaultsLayoutsRoute: typeof AppVaultsLayoutsRoute
  AppVaultsNewRoute: typeof AppVaultsNewRoute
  AppVaultsTabsRoute: typeof AppVaultsTabsRoute
  AppVaultsIndexRoute: typeof AppVaultsIndexRoute
}

const AppVaultsRouteRouteChildren: AppVaultsRouteRouteChildren = {
  AppVaultsVaultIdRouteRoute: AppVaultsVaultIdRouteRouteWithChildren,
  AppVaultsLayoutsRoute: AppVaultsLayoutsRoute,
  AppVaultsNewRoute: AppVaultsNewRoute,
  AppVaultsTabsRoute: AppVaultsTabsRoute,
  AppVaultsIndexRoute: AppVaultsIndexRoute,
}

const AppVaultsRouteRouteWithChildren = AppVaultsRouteRoute._addFileChildren(
  AppVaultsRouteRouteChildren,
)

interface AppRouteChildren {
  AppAccountRouteRoute: typeof AppAccountRouteRouteWithChildren
  AppAddressBookRouteRoute: typeof AppAddressBookRouteRouteWithChildren
  AppComplianceRouteRoute: typeof AppComplianceRouteRouteWithChildren
  AppIdentitiesRouteRoute: typeof AppIdentitiesRouteRouteWithChildren
  AppOperationsRouteRoute: typeof AppOperationsRouteRouteWithChildren
  AppPoliciesRouteRoute: typeof AppPoliciesRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppSignersRouteRoute: typeof AppSignersRouteRouteWithChildren
  AppVaultsRouteRoute: typeof AppVaultsRouteRouteWithChildren
  AppOverviewRoute: typeof AppOverviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRouteRoute: AppAccountRouteRouteWithChildren,
  AppAddressBookRouteRoute: AppAddressBookRouteRouteWithChildren,
  AppComplianceRouteRoute: AppComplianceRouteRouteWithChildren,
  AppIdentitiesRouteRoute: AppIdentitiesRouteRouteWithChildren,
  AppOperationsRouteRoute: AppOperationsRouteRouteWithChildren,
  AppPoliciesRouteRoute: AppPoliciesRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppSignersRouteRoute: AppSignersRouteRouteWithChildren,
  AppVaultsRouteRoute: AppVaultsRouteRouteWithChildren,
  AppOverviewRoute: AppOverviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiOpenapiAppRouteChildren {
  ApiOpenapiAppSchemaRoute: typeof ApiOpenapiAppSchemaRoute
}

const ApiOpenapiAppRouteChildren: ApiOpenapiAppRouteChildren = {
  ApiOpenapiAppSchemaRoute: ApiOpenapiAppSchemaRoute,
}

const ApiOpenapiAppRouteWithChildren = ApiOpenapiAppRoute._addFileChildren(
  ApiOpenapiAppRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRouteRoute: ForgotPasswordRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  SignUpRouteRoute: SignUpRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ApiOpenapiAppRoute: ApiOpenapiAppRouteWithChildren,
  ApiOpenapiAuthRoute: ApiOpenapiAuthRoute,
  ApiRestSplatRoute: ApiRestSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiDevEmailTemplateRoute: ApiDevEmailTemplateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
